#!/usr/bin/python3
"""Generate GNOME Shell and GTK CSS from reviewed Bunny design tokens."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[2]
TOKEN_DIR = ROOT / "visual" / "tokens"


def load(family: str) -> dict[str, object]:
    data = json.loads((TOKEN_DIR / f"{family}.json").read_text(encoding="utf-8"))
    if data.get("family") != family or data.get("version") != 1:
        raise ValueError(f"unexpected {family} token contract")
    return {name: token["value"] for name, token in data["tokens"].items()}


def render_shell() -> str:
    c, s, r, m, t = (load(name) for name in ("colors", "spacing", "radius", "motion", "typography"))
    return f"""/* Generated by visual/tools/generate_css.py. Do not hand edit. */
.bunny-v1-panel {{ background-color: {c['dark-surface']}; color: {c['dark-text']}; border-radius: {r['panel']}; padding: {s['space-4']}; box-shadow: 0 12px 36px rgba(0,0,0,.36); }}
.bunny-v1-card {{ background-color: {c['dark-elevated']}; border-radius: {r['card']}; padding: {s['space-3']}; spacing: {s['space-2']}; }}
.bunny-v1-top-button {{ border-radius: {r['control-small']}; padding: 0 {s['space-3']}; min-height: 32px; font-weight: {t['weight-semibold']}; }}
.bunny-v1-top-button:focus, .bunny-v1-action:focus, .bunny-v1-result:focus {{ box-shadow: inset 0 0 0 2px {c['dark-focus']}; }}
.bunny-v1-dock {{ background-color: rgba(21,24,33,.96); border-radius: {r['panel']}; padding: {s['space-2']}; spacing: {s['space-1']}; }}
.bunny-v1-dock-icon {{ border-radius: {r['control-small']}; padding: {s['space-2']}; min-width: 40px; min-height: 40px; }}
.bunny-v1-dock-icon:hover {{ background-color: {c['dark-elevated']}; }}
.bunny-v1-running {{ border-bottom: 3px solid {c['dark-accent']}; }}
.bunny-v1-entry {{ background-color: {c['dark-elevated']}; color: {c['dark-text']}; border-radius: {r['control-small']}; padding: {s['space-3']}; selection-background-color: {c['dark-accent']}; }}
.bunny-v1-result {{ border-radius: {r['control-small']}; padding: {s['space-3']}; min-height: 40px; }}
.bunny-v1-result:hover {{ background-color: {c['dark-elevated']}; }}
.bunny-v1-badge {{ border: 1px solid {c['dark-muted']}; border-radius: {r['pill']}; padding: 2px {s['space-2']}; font-size: {t['size-caption']}; }}
.bunny-v1-muted {{ color: {c['dark-muted']}; }}
.bunny-v1-danger {{ color: {c['dark-danger']}; }}
.bunny-v1-warning {{ color: {c['dark-warning']}; }}
.bunny-v1-success {{ color: {c['dark-success']}; }}
.bunny-v1-privacy {{ color: {c['dark-focus']}; font-weight: {t['weight-semibold']}; }}
.bunny-v1-mock {{ background-color: {c['dark-warning']}; color: {c['dark-background']}; border-radius: {r['control-small']}; padding: {s['space-2']}; font-weight: {t['weight-semibold']}; }}
.bunny-v1-compact .bunny-v1-card {{ padding: {s['space-2']}; spacing: {s['space-1']}; }}
.bunny-v1-compact .bunny-v1-dock-icon {{ min-width: 36px; min-height: 36px; padding: {s['space-1']}; }}
.bunny-v1-reduced-motion {{ transition-duration: 0ms; }}
.bunny-v1-light {{ background-color: {c['light-surface']}; color: {c['light-text']}; box-shadow: 0 12px 36px rgba(20,24,35,.16); }}
.bunny-v1-light .bunny-v1-card, .bunny-v1-light .bunny-v1-entry {{ background-color: {c['light-elevated']}; color: {c['light-text']}; }}
.bunny-v1-light .bunny-v1-muted {{ color: {c['light-muted']}; }}
.bunny-v1-high-contrast {{ background-color: {c['high-background']}; color: {c['high-text']}; border: 2px solid {c['high-text']}; box-shadow: none; }}
"""


def render_gtk() -> str:
    c, s, r, t = (load(name) for name in ("colors", "spacing", "radius", "typography"))
    return f"""/* Generated by visual/tools/generate_css.py. Do not hand edit. */
.bunny-window {{ font-family: \"{t['font-ui']}\", sans-serif; }}
.bunny-card {{ background: alpha(@window_fg_color, .055); border-radius: {r['card']}; padding: {s['space-4']}; }}
.bunny-panel {{ border-radius: {r['panel']}; padding: {s['space-5']}; }}
.bunny-mono {{ font-family: \"{t['font-mono']}\", monospace; font-size: {t['size-monospace']}; }}
.bunny-caption {{ font-size: {t['size-caption']}; opacity: .76; }}
.bunny-state {{ border-radius: {r['pill']}; padding: {s['space-1']} {s['space-2']}; font-weight: {t['weight-semibold']}; }}
.bunny-mock-banner {{ background: {c['dark-warning']}; color: {c['dark-background']}; border-radius: {r['control-small']}; padding: {s['space-2']}; font-weight: {t['weight-semibold']}; }}
.bunny-critical {{ border: 2px solid {c['dark-danger']}; }}
.bunny-privileged {{ border-left: 4px solid {c['dark-warning']}; }}
.bunny-standard {{ border-left: 4px solid {c['dark-accent']}; }}
.bunny-information {{ border-left: 4px solid {c['dark-focus']}; }}
button:focus-visible, row:focus-visible, entry:focus-visible, switch:focus-visible {{ outline: 2px solid {c['dark-focus']}; outline-offset: 2px; }}
.bunny-compact .bunny-card {{ padding: {s['space-2']}; border-radius: 12px; }}
.bunny-compact list row {{ min-height: 40px; }}
.bunny-reduced-motion * {{ transition-duration: 0ms; animation-duration: 0ms; }}
@media (prefers-contrast: more) {{ .bunny-card {{ border: 2px solid currentColor; background: transparent; }} }}
"""


TARGETS = {
    ROOT / "shell" / "bunny-shell-extension" / "stylesheet.css": render_shell,
    ROOT / "apps" / "common" / "bunny_visual" / "style.css": render_gtk,
}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale: list[str] = []
    for target, renderer in TARGETS.items():
        expected = renderer()
        if args.check:
            if not target.is_file() or target.read_text(encoding="utf-8") != expected:
                stale.append(str(target.relative_to(ROOT)))
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(expected, encoding="utf-8", newline="\n")
    if stale:
        print("Generated CSS is stale: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
