#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Render the host reports from the environment and readiness results.

Generated rather than written, for the reason the qualification reports are
generated: a report claiming a capability the environment report does not show is
the discrepancy the evidence model exists to prevent, and one source is the
cheapest way to prevent it.

Run with no environment, which is the current state, every report says NOT_RUN
and says why. Run against a real host, each report states what was observed.

    python render-host-reports.py                      # no host yet
    python render-host-reports.py --environment e.json --readiness r.json
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "reports"

HEADER = """<!--
SPDX-FileCopyrightText: 2026 ComradeArt
SPDX-License-Identifier: GPL-3.0-or-later
-->

<!-- GENERATED by infrastructure/fedora-host/scripts/render-host-reports.py
     Do not edit by hand. Every observation comes from the environment report. -->

"""

NOTICE = (
    "> **Host infrastructure report. This qualifies no Bunny OS artifact,**\n"
    "> **satisfies no prerequisite, and changes no release result.**\n"
    "> Stable release remains **NO-GO**. Pilots remain **BLOCKED**.\n\n"
)

NO_HOST = (
    "## Status: `NOT_RUN`\n\n"
    "No Fedora qualification host has been provisioned, so nothing in this report\n"
    "has been observed. It describes what will be measured, not what has been.\n\n"
    "The blocking dependency is hardware, not effort: see\n"
    "`infrastructure/fedora-host/OPERATOR_CHECKLIST.md`.\n"
)


def state(value, *, absent="`NOT_RUN`") -> str:
    """Render an observation, never inventing one."""
    if value is None or value == "" or value == []:
        return absent
    if isinstance(value, bool):
        return "`observed: true`" if value else "`observed: false`"
    if isinstance(value, list):
        return ", ".join(f"`{v}`" for v in value)
    return f"`{value}`"


def section(title: str, rows: list[tuple[str, str]]) -> str:
    lines = [f"## {title}", "", "| Property | Observed |", "|---|---|"]
    lines += [f"| {name} | {value} |" for name, value in rows]
    lines.append("")
    return "\n".join(lines)


def build(env: dict | None, readiness: dict | None) -> dict[str, str]:
    reports: dict[str, str] = {}

    def emit(filename: str, title: str, body: str) -> None:
        reports[filename] = HEADER + NOTICE + f"# {title}\n\n" + body

    if env is None:
        for filename, title in REPORT_TITLES.items():
            emit(filename, title, NO_HOST)
        return reports

    g, d, t = env["graphics"], env["displays"], env["tpm"]

    emit("HOST_INSTALLATION_REPORT.md", "Host installation report", section(
        "Installation", [
            ("Environment id", state(env["environmentId"])),
            ("Role", state(env["role"])),
            ("Operator", state(env["operator"])),
            ("Operating system", state(f"{env['os']['name']} {env['os']['versionId']}")),
            ("Kernel", state(env["os"]["kernel"])),
            ("ISO digest", state(env["os"].get("isoDigest"))),
            ("Installed on", state(env["os"].get("installedOn"))),
            ("Bare metal", state(env["host"]["bareMetal"])),
            ("Hypervisor detected", state(env["host"].get("hypervisorDetected"), absent="`none`")),
            ("Boot mode", state(env["boot"]["mode"])),
            ("Secure Boot", state(env["boot"]["secureBoot"])),
        ]))

    emit("HOST_ENVIRONMENT_REPORT.md", "Host environment report", section(
        "Machine", [
            ("Manufacturer", state(env["host"]["manufacturer"])),
            ("Model", state(env["host"]["model"])),
            ("Serial", "`hashed` — the raw serial is never committed"),
            ("CPU", state(env["cpu"]["model"])),
            ("Logical cores", state(env["cpu"]["logicalCores"])),
            ("Memory", state(f"{env['memory']['totalBytes'] / 1024**3:.1f} GiB")),
            ("Clock synchronised", state(env["clock"]["synchronised"])),
        ]) + section("Session", [
            ("Session type", state(env["session"]["type"])),
            ("Desktop", state(env["session"].get("desktop"))),
            ("SELinux", state(env["selinux"]["mode"])),
        ]))

    if readiness:
        rows = [
            (f"`{c['id']}`", ("**satisfied**" if c["satisfied"] else f"**BLOCKED** — {c['refusal']}"))
            for c in readiness["conditions"]
        ]
        body = (
            f"## Result: `{readiness['result']}`\n\n"
            f"{readiness['mandatorySatisfied']} of {readiness['mandatoryTotal']} "
            "mandatory conditions satisfied. Every condition is mandatory; there is no "
            "warning tier.\n\n"
            + section("Conditions", rows)
        )
        if readiness["result"] == "BLOCKED":
            body += (
                "\nThis host may not be used to qualify Bunny OS. A host that cannot "
                "measure a requirement must refuse the work rather than produce a result "
                "that resembles a measurement.\n"
            )
    else:
        body = NO_HOST
    emit("HOST_READINESS_REPORT.md", "Host readiness report", body)

    emit("GPU_REPORT.md", "GPU report", section("Renderer", [
        ("PCI identity", state(g.get("pciIdentity"))),
        ("Kernel driver", state(g.get("kernelDriver"))),
        ("Mesa / OpenGL", state(g.get("mesaVersion"))),
        ("OpenGL renderer", state(g.get("openglRenderer"))),
        ("Vulkan device", state(g.get("vulkanDevice"))),
        ("Software rasteriser", state(g["softwareRasteriser"])),
    ]) + (
        "\n**A software rasteriser never qualifies GPU rendering.** `llvmpipe` renders\n"
        "correctly and proves nothing about the hardware path. A translated device such\n"
        "as Direct3D12 is refused for the same reason, whatever it is named.\n"
        if g["softwareRasteriser"] or not g["drmCardNodes"] else ""
    ))

    emit("DRM_AND_DISPLAY_REPORT.md", "DRM and display report", section("DRM", [
        ("Card nodes", state(g["drmCardNodes"])),
        ("Render nodes", state(g["drmRenderNodes"])),
    ]) + section("Displays", [
        ("Connected outputs", state(d["connectedOutputs"])),
        ("Mixed resolution", state(d.get("mixedResolution"))),
    ] + [
        (f"`{o['connector']}`", f"`{o['status']}` {o.get('preferredMode') or ''}".strip())
        for o in d["outputs"]
    ]) + (
        "\nOnly connected DRM connectors count. Two nested windows are not two displays.\n"
    ))

    emit("KVM_REPORT.md", "KVM report", section("Virtualisation", [
        ("KVM available", state(env["virtualisation"]["kvmAvailable"])),
        ("QEMU", state(env["virtualisation"].get("qemuVersion"))),
        ("libvirt", state(env["virtualisation"].get("libvirtVersion"))),
        ("virt-host-validate", state(env["virtualisation"].get("virtHostValidate"))),
    ]) + (
        "\nDisposable guests run Programs E, F and G. **A guest result never enters a\n"
        "physical cell**, including a guest that ran on the physical qualification host.\n"
    ))

    emit("SELINUX_HOST_REPORT.md", "SELinux host report", section("Host SELinux", [
        ("Mode", state(env["selinux"]["mode"])),
    ]) + (
        "\nThe host runs enforcing. This is the host posture only — Program F measures\n"
        "the *installed system*, which is a separate subject with its own evidence.\n"
    ))

    emit("PIPEWIRE_PORTAL_REPORT.md", "PipeWire and portal report", section("Capture stack", [
        ("PipeWire", state(env["session"]["pipewire"])),
        ("WirePlumber", state(env["session"]["wireplumber"])),
        ("xdg-desktop-portal", state(env["session"]["portal"])),
        ("Portal backends", state(env["session"].get("portalBackends"))),
    ]) + (
        "\nPresence is not function. Screen sharing passes only when an external client\n"
        "receives actual frames through PipeWire after explicit portal approval.\n"
    ))

    emit("ACCESSIBILITY_HOST_REPORT.md", "Accessibility host report", section("Stack", [
        ("Orca installed", state(env["accessibility"]["orcaInstalled"])),
        ("Orca version", state(env["accessibility"].get("orcaVersion"))),
        ("speech-dispatcher", state(env["accessibility"]["speechDispatcherInstalled"])),
        ("AT-SPI present", state(env["accessibility"].get("atspiPresent"))),
    ]) + (
        "\nInstalled is not validated. Accessibility passes only when Orca actually\n"
        "navigates the shell; labels are not Orca evidence, and BrlAPI key generation is\n"
        "not braille-device qualification.\n"
    ))

    emit("INPUT_METHOD_HOST_REPORT.md", "Input method host report", section("Input methods", [
        ("Available", state(env["inputMethod"]["available"])),
        ("IBus", state(env["inputMethod"].get("ibusVersion"))),
        ("Fcitx 5", state(env["inputMethod"].get("fcitx5Version"))),
        ("Engines", state(env["inputMethod"].get("engines"))),
    ]) + (
        "\nAn installed engine is not a working input path. Input methods pass only when\n"
        "real non-Latin text reaches a real application.\n"
    ))

    emit("PACKAGE_INVENTORY.md", "Package inventory", section("Toolchain", [
        (f"`{name}`", state(version)) for name, version in sorted(env["tooling"].items())
    ]) + "\nHost evidence, never release evidence.\n")

    emit("STORAGE_AND_RETENTION_REPORT.md", "Storage and retention report", section("Storage", [
        ("Available for evidence", state(f"{env['storage']['availableBytesForEvidence'] / 1024**3:.0f} GiB")),
        ("Devices", state([dev["name"] for dev in env["storage"]["devices"]])),
    ]) + "\nSee `STORAGE_POLICY.md`. No VM disk and no git worktree inside the repository.\n")

    emit("RESET_PROCEDURE_REPORT.md", "Reset procedure report",
         "See `RESET_PROCEDURE.md` for scopes and guarantees.\n\n"
         "The reset script touches only resources named with the prefix it controls, "
         "reports unrecognised guests and disks rather than removing them, and refuses "
         "an unknown scope. `--dry-run` is the documented first step.\n")

    emit("TPM_HOST_REPORT.md", "TPM host report", section("TPM", [
        ("Present", state(t["present"])),
        ("Version", state(t.get("version"))),
        ("Manufacturer", state(t.get("manufacturer"))),
        ("Physical", state(t["physical"])),
    ]) + (
        "\n**An emulated TPM proves the software path, never the machine.** `swtpm`\n"
        "evidence is never physical TPM evidence.\n"
    ))

    return reports


REPORT_TITLES = {
    "HOST_INSTALLATION_REPORT.md": "Host installation report",
    "HOST_ENVIRONMENT_REPORT.md": "Host environment report",
    "HOST_READINESS_REPORT.md": "Host readiness report",
    "PACKAGE_INVENTORY.md": "Package inventory",
    "DRM_AND_DISPLAY_REPORT.md": "DRM and display report",
    "GPU_REPORT.md": "GPU report",
    "KVM_REPORT.md": "KVM report",
    "SELINUX_HOST_REPORT.md": "SELinux host report",
    "PIPEWIRE_PORTAL_REPORT.md": "PipeWire and portal report",
    "ACCESSIBILITY_HOST_REPORT.md": "Accessibility host report",
    "INPUT_METHOD_HOST_REPORT.md": "Input method host report",
    "STORAGE_AND_RETENTION_REPORT.md": "Storage and retention report",
    "RESET_PROCEDURE_REPORT.md": "Reset procedure report",
    "TPM_HOST_REPORT.md": "TPM host report",
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--environment", type=Path)
    parser.add_argument("--readiness", type=Path)
    args = parser.parse_args()

    env = json.loads(args.environment.read_text(encoding="utf-8")) if args.environment else None
    readiness = json.loads(args.readiness.read_text(encoding="utf-8")) if args.readiness else None

    OUT.mkdir(parents=True, exist_ok=True)
    for filename, body in build(env, readiness).items():
        (OUT / filename).write_text(body, encoding="utf-8", newline="\n")
        print(f"wrote reports/{filename}")

    if env is None:
        print("\nNo environment supplied: every report records NOT_RUN.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
