// Generated by visual-v2/tools/generate_css.py. Do not hand edit.
// VISUAL PROTOTYPE ONLY — NOT RELEASE QUALIFIED — DO NOT MERGE INTO MAIN

export const TOKENS = Object.freeze({
  "layout": {
    "characterIllustrationHeight": 300,
    "characterMaximumPanelRatio": 0.45,
    "characterMinimumPanelHeight": 640,
    "dockHeight": 68,
    "dockHeightCompact": 54,
    "dockIcon": 48,
    "dockIconCompact": 38,
    "dockMaximumWidth": 660,
    "dockTexture": 38,
    "dockTextureCompact": 30,
    "edgeMargin": 20,
    "iconIdentity": 18,
    "iconSmall": 16,
    "iconStandard": 20,
    "paletteWidth": 680,
    "paletteWidthCompact": 580,
    "panelMaximumWidth": 480,
    "panelMinimumHeight": 420,
    "panelMinimumWidth": 320,
    "quickTileMinimumHeight": 76,
    "topBarHeight": 42,
    "topOffset": 54
  },
  "motion": {
    "micro": 120,
    "mode": 240,
    "panel": 180,
    "workspace": 280
  },
  "opacity": {
    "disabled": 0.46,
    "opaque": 1.0,
    "panel": 0.92,
    "secondary": 0.72
  },
  "radii": {
    "card": 16,
    "control": 12,
    "modal": 24,
    "panel": 22,
    "small": 8
  },
  "spacing": {
    "2xl": 32,
    "3xl": 48,
    "4xl": 64,
    "lg": 16,
    "md": 12,
    "sm": 8,
    "xl": 24,
    "xs": 4
  }
});
