// Generated by visual-v2/tools/generate_css.py. Do not hand edit.
// VISUAL PROTOTYPE ONLY — NOT RELEASE QUALIFIED — DO NOT MERGE INTO MAIN

export const TOKENS = Object.freeze({
  "motion": {
    "micro": 120,
    "mode": 240,
    "panel": 180,
    "workspace": 280
  },
  "opacity": {
    "disabled": 0.46,
    "opaque": 1.0,
    "panel": 0.92,
    "secondary": 0.72
  },
  "radii": {
    "card": 16,
    "control": 12,
    "modal": 24,
    "panel": 22,
    "small": 8
  },
  "spacing": {
    "2xl": 32,
    "3xl": 48,
    "4xl": 64,
    "lg": 16,
    "md": 12,
    "sm": 8,
    "xl": 24,
    "xs": 4
  }
});
