# SPDX-FileCopyrightText: 2026 ComradeArt
# SPDX-License-Identifier: GPL-3.0-or-later
"""Plan identity: what makes two plans the same plan, and one of them stale.

An execution plan is produced at one instant and applied at another. Between
those two instants the machine can change, the policy can change, the manifests
can change, and a newer plan can be generated by a different caller. Applying a
plan without being able to say *which* plan it is, and *what it was decided
against*, is how a system ends up starting a service sized for memory that was
freed ten minutes ago.

So every plan carries an identity block, and every field in it exists to answer
a question the applicator asks before it acts:

``planId``
    Which plan is this? Content-derived, so it is stable across processes and
    hosts and can be compared without a registry.
``revision``
    Which generation? Monotonic along a chain of reevaluations. Higher wins;
    a lower revision arriving after a higher one is a replay and is refused.
``inventoryFingerprint``
    What was the machine when this was decided? If it no longer matches, the
    decision was made against hardware that is not the hardware in front of us.
``budgetFingerprint``
    What could be spent when this was decided?
``policyFingerprint``
    What was permitted when this was decided? A plan that permitted remote
    execution must not be applied after the user withdrew that permission.
``registryFingerprint``
    What did the services declare when this was decided? A manifest that changed
    underneath a plan may have changed the memory the plan is about to grant.

**Fingerprints are of content, not of objects.** Everything is canonicalised —
sorted keys, no insignificant whitespace, a fixed number format — before it is
hashed, so two processes that computed the same decision from the same inputs
agree on its identity. A fingerprint that depended on dictionary insertion order
would make plan identity a property of the interpreter rather than of the plan.

**Fingerprints carry nothing that identifies the machine.** The inventory model
collects no serial numbers, MAC addresses or hostnames in the first place, and
the projection hashed here narrows further: volatile timing (when discovery ran,
how long it took) is excluded, because a plan is not a different plan for having
been decided a second later, and because a per-run timestamp inside a
fingerprint would make every plan unique and every comparison useless.
"""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
from typing import Any, Mapping

__all__ = [
    "DEFAULT_MAXIMUM_AGE_SECONDS",
    "FINGERPRINT_LENGTH",
    "PlanIdentity",
    "REEVALUATION_REASONS",
    "budget_fingerprint",
    "canonical_json",
    "digest",
    "inventory_fingerprint",
    "plan_content_digest",
    "policy_fingerprint",
    "registry_fingerprint",
]

#: Hex characters kept from each SHA-256. 128 bits: far beyond any collision
#: risk for a per-machine set of plans, and short enough to appear in a log line
#: and in a person's terminal without wrapping.
FINGERPRINT_LENGTH = 32

#: How long a plan may sit before the applicator refuses to apply it without a
#: fresh evaluation. Five minutes is longer than any transition takes and much
#: shorter than the interval over which a machine's free memory is meaningful.
#: Expiry is a backstop, not the primary defence: apply-time revalidation checks
#: the actual numbers, and this only bounds how wrong a plan can be before
#: anyone looks.
DEFAULT_MAXIMUM_AGE_SECONDS = 300.0

#: Why a plan was regenerated. Fixed so that an audit trail can be read by
#: machine, and so that the monitor's event vocabulary and the plan's stated
#: cause cannot drift apart. ``initial`` is the first plan of a process; the
#: rest correspond one-to-one with :data:`capability.apply.monitor.EVENTS`.
REEVALUATION_REASONS = (
    "initial",
    "operator_requested",
    "memory_pressure_entered",
    "memory_pressure_recovered",
    "thermal_limit_entered",
    "thermal_limit_recovered",
    "battery_critical",
    "battery_recovered",
    "network_lost",
    "network_restored",
    "display_attached",
    "display_removed",
    "audio_device_changed",
    "cpu_saturation_entered",
    "cpu_saturation_recovered",
    "gpu_memory_pressure_entered",
    "gpu_memory_pressure_recovered",
    "service_failed",
    "remote_provider_unavailable",
    "user_policy_changed",
    "manifest_registry_changed",
    "apply_time_validation_failed",
)


def canonical_json(value: Any) -> str:
    """Serialize ``value`` so that equal content produces an equal string.

    Sorted keys and compact separators remove the two ways a JSON document can
    differ without differing: key order and whitespace. ``ensure_ascii`` is left
    on so that the byte sequence is identical regardless of the encoding the
    caller happens to be writing with, which matters when a fingerprint computed
    on one host is compared against one computed on another.
    """
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True, default=_fallback)


def _fallback(value: Any) -> Any:
    """Refuse to hash anything whose serialization is not defined.

    A silent ``str(value)`` here would let an object with a memory address in
    its ``repr`` into a fingerprint, and every plan would then be unique. Types
    that reach this function are a bug in the projection functions below, so
    they raise rather than degrade.
    """
    if isinstance(value, (set, frozenset)):
        raise TypeError(
            "a set has no defined order and must not be fingerprinted; "
            "sort it into a list at the projection instead"
        )
    if isinstance(value, tuple):
        return list(value)
    raise TypeError(f"{type(value).__name__} has no canonical JSON form and cannot be fingerprinted")


def digest(value: Any) -> str:
    """The truncated SHA-256 of ``value``'s canonical form."""
    return hashlib.sha256(canonical_json(value).encode("ascii")).hexdigest()[:FINGERPRINT_LENGTH]


# --------------------------------------------------------------------------- #
# Projections
#
# Each of these narrows a document to the part a decision actually depended on.
# Hashing the whole document would be simpler and wrong: it would make a plan
# stale because discovery took 3 ms rather than 2, and it would put a wall-clock
# timestamp inside an identity that is supposed to be comparable.
# --------------------------------------------------------------------------- #


def inventory_fingerprint(inventory: Any) -> str:
    """Fingerprint the machine as the engine saw it.

    Excludes ``detectedAt`` and the probe timing block. A plan decided against
    16 GB of RAM at 09:00 was decided against the same machine as one decided at
    09:01, and treating those as different plans would make every reevaluation
    look like a hardware change. Probe *outcomes* are kept — a probe that failed
    this time and succeeded last time genuinely is a different machine as far as
    a decision is concerned — but their durations are not.
    """
    document = dict(inventory.to_json())
    document.pop("detectedAt", None)
    document.pop("privacy", None)
    detection = document.pop("detection", None)
    if isinstance(detection, Mapping):
        document["probeStates"] = sorted(
            (str(item.get("name", "")), str(item.get("state", "")))
            for item in detection.get("probes", [])
            if isinstance(item, Mapping)
        )
    return digest(document)


def budget_fingerprint(budget: Any) -> str:
    """Fingerprint what the engine was allowed to spend."""
    return digest(budget.to_json())


def policy_fingerprint(policy: Any) -> str:
    """Fingerprint what the engine was permitted to do.

    ``source`` and ``warnings`` are excluded: they say where a policy came from
    and what was odd about it, not what it permits. Two identical policies read
    from two different paths must not produce different plan identities, or a
    ``--policy`` flag in a test would look like a policy change to the
    applicator.
    """
    document = dict(policy.to_json())
    document.pop("source", None)
    document.pop("warnings", None)
    return digest(document)


def registry_fingerprint(registry: Any) -> str:
    """Fingerprint every manifest the engine consulted, in a fixed order.

    The whole manifest is hashed rather than a version field, because a manifest
    with the same version and a different ``minimumBytes`` is exactly the change
    this fingerprint exists to catch.
    """
    return digest([service.to_json() for service in registry.ordered()])


def plan_content_digest(
    decisions: Any,
    *,
    inventory: str,
    budget: str,
    policy: str,
    registry: str,
) -> str:
    """The digest of what a plan *says*, independent of when it was said.

    Two plans with the same content digest are the same desired state. That is
    the comparison reconciliation cares about: a reevaluation that produced an
    identical plan needs no transitions, whatever its revision number.
    """
    return digest({
        "decisions": [decision.to_json() for decision in decisions],
        "inventory": inventory,
        "budget": budget,
        "policy": policy,
        "registry": registry,
    })


@dataclass(frozen=True)
class PlanIdentity:
    """Everything needed to decide whether a plan may still be applied."""

    plan_id: str
    schema_version: int
    revision: int
    content_digest: str
    inventory_fingerprint: str
    budget_fingerprint: str
    policy_fingerprint: str
    registry_fingerprint: str
    #: Wall-clock, for a person reading an audit record.
    created_at: str = ""
    #: The engine's clock reading, for the applicator's arithmetic. Wall clock
    #: is not used for staleness: it steps when NTP corrects it, and a plan that
    #: became an hour old because a clock jumped is not a stale plan.
    created_at_monotonic: float = 0.0
    maximum_age_seconds: float = DEFAULT_MAXIMUM_AGE_SECONDS
    previous_plan_id: str | None = None
    reevaluation_reason: str = "initial"

    def __post_init__(self) -> None:
        if self.reevaluation_reason not in REEVALUATION_REASONS:
            raise ValueError(f"unknown reevaluation reason: {self.reevaluation_reason!r}")
        if self.revision < 1:
            raise ValueError("plan revision starts at 1 and only increases")

    def age_seconds(self, now: float) -> float:
        """How long this plan has existed, on the engine's clock.

        Clamped at zero. A negative age means the caller passed a clock reading
        from before the plan was made, which is a caller bug, not a plan that
        will expire in the future.
        """
        return max(0.0, now - self.created_at_monotonic)

    def expired(self, now: float) -> bool:
        if self.maximum_age_seconds <= 0:
            return False
        return self.age_seconds(now) > self.maximum_age_seconds

    def supersedes(self, other: "PlanIdentity | None") -> bool:
        """Whether this plan may replace ``other``.

        Strictly greater, so that a replayed plan at the same revision cannot
        displace the one already in force even if its content differs.
        """
        return other is None or self.revision > other.revision

    def describes_same_desired_state(self, other: "PlanIdentity | None") -> bool:
        return other is not None and self.content_digest == other.content_digest

    def to_json(self) -> dict[str, Any]:
        return {
            "planId": self.plan_id,
            "schemaVersion": self.schema_version,
            "revision": self.revision,
            "contentDigest": self.content_digest,
            "fingerprints": {
                "inventory": self.inventory_fingerprint,
                "budget": self.budget_fingerprint,
                "policy": self.policy_fingerprint,
                "registry": self.registry_fingerprint,
            },
            "createdAt": self.created_at,
            "createdAtMonotonic": self.created_at_monotonic,
            "maximumAgeSeconds": self.maximum_age_seconds,
            "previousPlanId": self.previous_plan_id,
            "reevaluationReason": self.reevaluation_reason,
        }

    @classmethod
    def from_json(cls, document: Mapping[str, Any]) -> "PlanIdentity":
        """Parse an identity block. Refuses anything it cannot check.

        A plan arriving from disk or from another process is untrusted
        structured input. Every field is type-checked here rather than being
        read lazily at the point of use, because a missing fingerprint that
        surfaces as ``None != "abc"`` would read as *"the machine changed"* and
        send the applicator into a reevaluation loop instead of reporting a
        malformed document.
        """
        if not isinstance(document, Mapping):
            raise ValueError("plan identity must be an object")
        fingerprints = document.get("fingerprints")
        if not isinstance(fingerprints, Mapping):
            raise ValueError("plan identity requires a fingerprints object")

        def text(source: Mapping[str, Any], key: str) -> str:
            value = source.get(key)
            if not isinstance(value, str) or not value:
                raise ValueError(f"plan identity field {key!r} must be a non-empty string")
            return value

        def number(key: str, default: float) -> float:
            value = document.get(key, default)
            if isinstance(value, bool) or not isinstance(value, (int, float)):
                raise ValueError(f"plan identity field {key!r} must be a number")
            return float(value)

        revision = document.get("revision")
        if isinstance(revision, bool) or not isinstance(revision, int):
            raise ValueError("plan identity revision must be an integer")
        schema_version = document.get("schemaVersion")
        if isinstance(schema_version, bool) or not isinstance(schema_version, int):
            raise ValueError("plan identity schemaVersion must be an integer")

        previous = document.get("previousPlanId")
        if previous is not None and not isinstance(previous, str):
            raise ValueError("previousPlanId must be a string or null")

        return cls(
            plan_id=text(document, "planId"),
            schema_version=schema_version,
            revision=revision,
            content_digest=text(document, "contentDigest"),
            inventory_fingerprint=text(fingerprints, "inventory"),
            budget_fingerprint=text(fingerprints, "budget"),
            policy_fingerprint=text(fingerprints, "policy"),
            registry_fingerprint=text(fingerprints, "registry"),
            created_at=str(document.get("createdAt", "")),
            created_at_monotonic=number("createdAtMonotonic", 0.0),
            maximum_age_seconds=number("maximumAgeSeconds", DEFAULT_MAXIMUM_AGE_SECONDS),
            previous_plan_id=previous,
            reevaluation_reason=str(document.get("reevaluationReason", "initial")),
        )


def build_identity(
    decisions: Any,
    *,
    inventory: Any,
    budget: Any,
    policy: Any,
    registry: Any,
    schema_version: int,
    created_at: str,
    now: float,
    previous: PlanIdentity | None = None,
    reason: str = "initial",
    maximum_age_seconds: float = DEFAULT_MAXIMUM_AGE_SECONDS,
) -> PlanIdentity:
    """Compute the identity of a freshly generated plan.

    The plan id folds in the revision and the previous plan id as well as the
    content, so a chain of reevaluations that keeps arriving at the same answer
    still produces distinguishable plans — the content digest is what says they
    are the same desired state, and it is kept separately for exactly that
    comparison. Both are deterministic: the same chain of inputs produces the
    same ids on any host, which is what lets the tests assert on them.
    """
    inventory_hash = inventory_fingerprint(inventory)
    budget_hash = budget_fingerprint(budget)
    policy_hash = policy_fingerprint(policy)
    registry_hash = registry_fingerprint(registry)
    content = plan_content_digest(
        decisions,
        inventory=inventory_hash, budget=budget_hash,
        policy=policy_hash, registry=registry_hash,
    )
    revision = (previous.revision + 1) if previous is not None else 1
    plan_id = "plan-" + digest({
        "content": content,
        "revision": revision,
        "previous": previous.plan_id if previous is not None else None,
    })[:16]
    return PlanIdentity(
        plan_id=plan_id,
        schema_version=schema_version,
        revision=revision,
        content_digest=content,
        inventory_fingerprint=inventory_hash,
        budget_fingerprint=budget_hash,
        policy_fingerprint=policy_hash,
        registry_fingerprint=registry_hash,
        created_at=created_at,
        created_at_monotonic=now,
        maximum_age_seconds=maximum_age_seconds,
        previous_plan_id=previous.plan_id if previous is not None else None,
        reevaluation_reason=reason,
    )
