# SPDX-FileCopyrightText: 2026 ComradeArt
# SPDX-License-Identifier: GPL-3.0-or-later
"""Fixtures for the speech-input suite: barriers, scripted devices, real PCM.

The two rules of :mod:`tests.companion.voice_support` run through everything
here. **Barriers, not sleeps**: every place a test must be *inside* an
operation — cancelling during capture, removing the device mid-utterance,
confirming while a retry lands — is a :class:`threading.Event` the fake waits
on and the test releases. **Real audio where audio is the point**: the frames
the scripted device delivers are genuine 16-bit PCM with a speech-shaped
envelope, generated by :func:`speech_pcm`, so the energy detector is exercised
on the waveform it will meet rather than on a list of numbers.

The scripted backend and recogniser implement the real contracts —
:class:`companion.speech.capture.CaptureBackend` and
:class:`companion.speech.recognizer.SpeechRecognizer` — rather than being
mocks with the methods a test happens to call, so the protocols cannot drift.
The scripted *handle* mirrors :class:`companion.speech.capture.CaptureHandle`'s
whole surface, buffer included, because the worker's capture loop reads all of
it.
"""

from __future__ import annotations

from dataclasses import dataclass
import math
import struct
import threading
import time
from typing import Any, Callable, Sequence

from companion.speech.capture import (
    BoundedFrameBuffer,
    CaptureBackendHealth,
    CaptureDevice,
)
from companion.speech.recognizer import (
    RecognizerDeclaration,
    RecognizerHealth,
    RecognizerRegistry,
    RecognizerResourceEstimate,
)
from companion.speech.request import SpeechInputRequest
from companion.speech.transcript import FinalTranscript, PartialTranscript

__all__ = [
    "BARRIER_TIMEOUT",
    "FrameScript",
    "ScriptedCaptureBackend",
    "ScriptedRecognizer",
    "RecordingSink",
    "collect_events",
    "make_request",
    "silence_pcm",
    "speech_pcm",
]

#: How long any barrier in this suite waits before giving up: long enough that
#: a loaded machine does not fail spuriously, short enough that a deadlock is
#: reported rather than hung on.
BARRIER_TIMEOUT = 10.0


def speech_pcm(seconds: float, *, sample_rate: int = 16_000, channels: int = 1) -> bytes:
    """Raw 16-bit PCM whose loudness varies like speech.

    120 ms blocks alternating loud and quiet, matching
    :func:`tests.companion.voice_support.write_wav`'s envelope: several blocks
    cross the energy gate and several sit under it, so speech detection is a
    property of the waveform rather than of the fixture being uniformly loud.
    """
    frames = int(seconds * sample_rate)
    data = bytearray()
    for index in range(frames):
        moment = index / sample_rate
        block = int(moment / 0.12)
        level = (0.15, 0.9, 0.45, 0.6)[block % 4]
        value = level * math.sin(2 * math.pi * 220 * moment)
        sample = struct.pack("<h", int(max(-1.0, min(1.0, value)) * 32000))
        data += sample * channels
    return bytes(data)


def silence_pcm(seconds: float, *, sample_rate: int = 16_000, channels: int = 1) -> bytes:
    """Raw silence: zero-valued frames delivered on schedule, as a quiet room is."""
    return b"\x00\x00" * int(seconds * sample_rate) * channels


def make_request(
    *,
    request_id: str = "speechreq-1",
    session_id: str = "session-1",
    activation_source: str = "push-to-talk-button",
    maximum_capture_seconds: float = 8.0,
    initial_silence_seconds: float = 2.0,
    endpoint_silence_seconds: float = 0.4,
    **extra: Any,
) -> SpeechInputRequest:
    return SpeechInputRequest(
        request_id=request_id,
        session_id=session_id,
        activation_source=activation_source,
        maximum_capture_seconds=maximum_capture_seconds,
        initial_silence_seconds=initial_silence_seconds,
        endpoint_silence_seconds=endpoint_silence_seconds,
        **extra,
    )


def collect_events(worker: Any) -> tuple[list[Any], Callable[[], list[str]]]:
    """Subscribe to a worker and return the list plus a kinds-only view."""
    received: list[Any] = []
    lock = threading.Lock()

    def _observe(event: Any) -> None:
        with lock:
            received.append(event)

    worker.subscribe(_observe)

    def kinds() -> list[str]:
        with lock:
            return [item.kind for item in received]

    return received, kinds


class RecordingSink:
    """An indicator sink that displays by recording, and can refuse to."""

    def __init__(self, *, can_display: bool = True) -> None:
        self.can_display = can_display
        self.shown: list[dict[str, Any]] = []
        self.cleared: list[dict[str, Any]] = []
        self.shown_at: list[float] = []
        self.cleared_at: list[float] = []

    def show(self, state: Any) -> bool:
        if not self.can_display:
            return False
        self.shown.append(state.to_json())
        self.shown_at.append(time.monotonic())
        return True

    def clear(self, state: Any) -> bool:
        self.cleared.append(state.to_json())
        self.cleared_at.append(time.monotonic())
        return True


# --------------------------------------------------------------------------- #
# A capture device a test can steer
# --------------------------------------------------------------------------- #


class FrameScript:
    """The frames a scripted device will deliver, and when.

    A test pushes chunks (or queues them at construction) and the handle's
    ``read`` drains them. ``end()`` is the device going away: ``running``
    turns false and reads return nothing, which is exactly the shape a
    recorder's death presents to the worker. ``hold`` is a barrier: while
    set, reads return nothing but the device is alive — the state a test
    needs to be *inside* to cancel mid-capture deterministically.
    """

    def __init__(self, chunks: Sequence[bytes] = ()) -> None:
        self._chunks: list[bytes] = list(chunks)
        self._guard = threading.Lock()
        self._ended = False
        self.hold = threading.Event()
        self.first_read = threading.Event()

    def push(self, chunk: bytes) -> None:
        with self._guard:
            self._chunks.append(chunk)

    def end(self) -> None:
        with self._guard:
            self._ended = True

    @property
    def ended(self) -> bool:
        with self._guard:
            return self._ended

    def take(self) -> bytes:
        self.first_read.set()
        if self.hold.is_set():
            return b""
        with self._guard:
            if not self._chunks:
                return b""
            return self._chunks.pop(0)


class _ScriptedHandle:
    """A capture handle with no recorder behind it. The worker's whole surface."""

    def __init__(
        self,
        *,
        request: SpeechInputRequest,
        backend_id: str,
        device_id: str,
        script: FrameScript,
        fail_start: str = "",
        opened: threading.Event | None = None,
    ) -> None:
        self.request_id = request.request_id
        self.backend_id = backend_id
        self.device_id = device_id
        self.buffer = BoundedFrameBuffer(
            maximum_total_bytes=request.maximum_capture_bytes,
        )
        self._script = script
        self._fail_start = fail_start
        self._closed = False
        self._stopped = False
        self._guard = threading.RLock()
        self.requested_at = time.monotonic()
        self.opened_at = self.requested_at
        self.first_frame_at = 0.0
        if opened is not None:
            opened.set()

    @property
    def started(self) -> bool:
        return not self._fail_start

    @property
    def start_error(self) -> str:
        return self._fail_start

    @property
    def closed(self) -> bool:
        with self._guard:
            return self._closed

    @property
    def open_latency_seconds(self) -> float:
        return 0.0

    @property
    def first_frame_latency_seconds(self) -> float:
        return 0.0

    @property
    def bytes_captured(self) -> int:
        return self.buffer.total_bytes

    def running(self) -> bool:
        return not self._stopped and not self._script.ended and not self.buffer.exhausted

    def exit_code(self) -> int | None:
        return 0 if (self._stopped or self._script.ended) else None

    def read(self, *, timeout: float = 0.05) -> bytes:
        chunk = self._script.take()
        if chunk:
            if not self.first_frame_at:
                self.first_frame_at = time.monotonic()
            # Through the real bounded buffer, so overrun and budget
            # accounting are the production code's own.
            self.buffer.push(chunk)
            return self.buffer.read(timeout=0.0)
        if timeout:
            time.sleep(min(timeout, 0.005))
        return b""

    def stop(self) -> None:
        self._stopped = True

    def close(self) -> "_ScriptedHandle":
        with self._guard:
            self._closed = True
        self._stopped = True
        self.buffer.close()
        return self

    def describe(self) -> dict[str, Any]:
        return {"requestId": self.request_id, "closed": self.closed}


class ScriptedCaptureBackend:
    """A real :class:`companion.speech.capture.CaptureBackend` a test drives."""

    def __init__(
        self,
        backend_id: str = "scripted-capture",
        *,
        kind: str = "scripted",
        devices: Sequence[str] = ("scripted-mic",),
        monitors: Sequence[str] = (),
        reachable: bool = True,
        fail_start: str = "",
        script: FrameScript | None = None,
        opened: threading.Event | None = None,
    ) -> None:
        self.backend_id = backend_id
        self.kind = kind
        self._devices = list(devices)
        self._monitors = list(monitors)
        self._reachable = reachable
        self.fail_start = fail_start
        self.script = script or FrameScript()
        self.opened = opened
        self.closed = False
        self.opens = 0
        self.handles: list[_ScriptedHandle] = []

    def set_reachable(self, value: bool) -> None:
        self._reachable = value

    def set_devices(self, devices: Sequence[str]) -> None:
        self._devices = list(devices)

    def record(self, succeeded: bool) -> None:
        return None

    def health(self, *, monotonic: float = 0.0, refresh: bool = False) -> CaptureBackendHealth:
        usable = len(self._devices) if self._reachable else 0
        return CaptureBackendHealth(
            backend_id=self.backend_id,
            kind=self.kind,
            available=not self.closed,
            reachable=self._reachable,
            device_count=usable,
            default_device=self._devices[0] if self._devices and self._reachable else "",
            detail="" if self._reachable else "the scripted audio server is not answering",
            checked_at_monotonic=monotonic,
        )

    def discover(self) -> Sequence[CaptureDevice]:
        if not self._reachable:
            return ()
        found = [
            CaptureDevice(
                device_id=name, backend_id=self.backend_id, name=name,
                default=index == 0, state="RUNNING",
            )
            for index, name in enumerate(self._devices)
        ]
        found.extend(
            CaptureDevice(
                device_id=name, backend_id=self.backend_id, name=name,
                state="RUNNING", monitor=True,
            )
            for name in self._monitors
        )
        return tuple(found)

    def default_device(self) -> CaptureDevice | None:
        devices = [item for item in self.discover() if not item.monitor]
        return devices[0] if devices else None

    def supports(self, request: SpeechInputRequest) -> tuple[bool, str]:
        return True, ""

    def open(
        self,
        request: SpeechInputRequest,
        *,
        device_id: str = "",
        buffer: BoundedFrameBuffer | None = None,
    ) -> _ScriptedHandle:
        self.opens += 1
        handle = _ScriptedHandle(
            request=request,
            backend_id=self.backend_id,
            device_id=device_id or (self._devices[0] if self._devices else ""),
            script=self.script,
            fail_start=self.fail_start,
            opened=self.opened,
        )
        self.handles.append(handle)
        return handle

    def close(self) -> None:
        self.closed = True


# --------------------------------------------------------------------------- #
# A recogniser a test can steer
# --------------------------------------------------------------------------- #


class _ScriptedSession:
    def __init__(self, recognizer: "ScriptedRecognizer", request: SpeechInputRequest) -> None:
        self._recognizer = recognizer
        self._request = request
        self._revision = 0
        self._bytes = 0
        self._cancelled = False
        self._words: list[str] = []
        self.closed = False

    def accept(self, frames: bytes, *, position_seconds: float = 0.0) -> PartialTranscript | None:
        recognizer = self._recognizer
        recognizer.accepted_bytes += len(frames)
        if recognizer.accept_entered is not None:
            recognizer.accept_entered.set()
        if recognizer.accept_gate is not None:
            recognizer.accept_gate.wait(BARRIER_TIMEOUT)
        if recognizer.failure_mode == "crash-on-accept":
            raise RuntimeError("the scripted recogniser crashed on submitted frames")
        if self._cancelled or not frames:
            return None
        self._bytes += len(frames)
        words = recognizer.final_text.split()
        heard = min(len(words), 1 + self._bytes // recognizer.bytes_per_partial)
        if heard <= len(self._words):
            return None
        self._words = words[:heard]
        self._revision += 1
        try:
            return PartialTranscript(
                request_id=self._request.request_id,
                revision=self._revision,
                text=" ".join(self._words),
                provider_id=recognizer.provider_id,
                implementation_id=recognizer.declaration.implementation_id,
                confidence=0.5,
                position_seconds=position_seconds,
            )
        except Exception:  # noqa: BLE001 - over-bound partials are dropped, as vosk's are
            return None

    def finish(self) -> FinalTranscript:
        recognizer = self._recognizer
        if recognizer.finish_entered is not None:
            recognizer.finish_entered.set()
        if recognizer.finish_gate is not None:
            recognizer.finish_gate.wait(BARRIER_TIMEOUT)
        if recognizer.failure_mode == "crash-on-finish":
            raise RuntimeError("the scripted recogniser crashed at finalisation")
        if self._cancelled:
            raise RuntimeError("this recognition was cancelled and has no answer")
        text = recognizer.final_text if self._bytes else ""
        if recognizer.failure_mode == "empty":
            text = ""
        return FinalTranscript(
            request_id=self._request.request_id,
            session_id=self._request.session_id,
            text=text,
            provider_id=recognizer.provider_id,
            implementation_id=recognizer.declaration.implementation_id,
            language=self._request.language,
            confidence=0.9,
            audio_ended_at=self._bytes / max(1, self._request.bytes_per_second),
            recognition_mode="streaming",
        )

    def cancel(self) -> None:
        self._cancelled = True
        self._recognizer.cancelled.append(self._request.request_id)

    def close(self) -> None:
        self.closed = True
        self._recognizer.closed_sessions += 1


class ScriptedRecognizer:
    """A real :class:`companion.speech.recognizer.SpeechRecognizer` a test drives.

    Every §16 and §22 condition is a constructor argument, so a test reads as
    one line describing the recogniser it is pretending to have installed.
    """

    def __init__(
        self,
        provider_id: str = "scripted-recognizer",
        *,
        available: bool = True,
        supports_streaming: bool = True,
        supports_partials: bool = True,
        languages: Sequence[str] = ("en",),
        final_text: str = "count the words in this note",
        bytes_per_partial: int = 16_000,
        failure_mode: str = "",
        start_gate: threading.Event | None = None,
        start_entered: threading.Event | None = None,
        accept_gate: threading.Event | None = None,
        accept_entered: threading.Event | None = None,
        finish_gate: threading.Event | None = None,
        finish_entered: threading.Event | None = None,
        model_memory_bytes: int = 64 * 1024 * 1024,
    ) -> None:
        self.provider_id = provider_id
        self._available = available
        self.final_text = final_text
        self.bytes_per_partial = max(1, bytes_per_partial)
        self.failure_mode = failure_mode
        self.start_gate = start_gate
        self.start_entered = start_entered
        self.accept_gate = accept_gate
        self.accept_entered = accept_entered
        self.finish_gate = finish_gate
        self.finish_entered = finish_entered
        self.accepted_bytes = 0
        self.sessions: list[_ScriptedSession] = []
        self.cancelled: list[str] = []
        self.closed_sessions = 0
        self.closed = False
        self._declaration = RecognizerDeclaration(
            provider_id=provider_id,
            implementation_id=f"{provider_id}/test",
            local=True,
            languages=tuple(languages),
            locales=("en-GB", "en-US"),
            supports_streaming=supports_streaming,
            supports_partial_transcripts=supports_partials,
            provides_confidence=True,
            audio_formats=("raw-pcm-s16le",),
            sample_rates=(16_000, 22_050, 44_100, 48_000),
            resource_estimate=RecognizerResourceEstimate(
                model_memory_bytes=model_memory_bytes,
            ),
        )

    @property
    def declaration(self) -> RecognizerDeclaration:
        return self._declaration

    def set_available(self, value: bool) -> None:
        self._available = value

    def health(self, *, monotonic: float = 0.0, refresh: bool = False) -> RecognizerHealth:
        return RecognizerHealth(
            provider_id=self.provider_id,
            available=self._available and not self.closed,
            healthy=True,
            detail="" if self._available else "the scripted recogniser is unavailable",
            checked_at_monotonic=monotonic,
        )

    def start(self, request: SpeechInputRequest) -> _ScriptedSession:
        if self.start_entered is not None:
            self.start_entered.set()
        if self.start_gate is not None:
            self.start_gate.wait(BARRIER_TIMEOUT)
        if self.failure_mode == "crash-on-start":
            raise RuntimeError("the scripted recogniser could not start")
        session = _ScriptedSession(self, request)
        self.sessions.append(session)
        return session

    def close(self) -> None:
        self.closed = True


def scripted_registry(*recognizers: ScriptedRecognizer) -> RecognizerRegistry:
    return RecognizerRegistry(list(recognizers) or [ScriptedRecognizer()])


def wait_for(predicate: Callable[[], Any], timeout: float = BARRIER_TIMEOUT) -> bool:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if predicate():
            return True
        time.sleep(0.005)
    return bool(predicate())


@dataclass
class WorkerHarness:
    """One capture worker with every collaborator reachable for assertions."""

    worker: Any
    backend: ScriptedCaptureBackend
    recognizer: ScriptedRecognizer
    router: Any
    policy: Any
    indicator: Any
    ledger: Any
    sink: RecordingSink
    journal: Any
    coordinator: Any

    def close(self) -> None:
        self.worker.close()


def build_worker(
    *,
    backend: ScriptedCaptureBackend | None = None,
    recognizer: ScriptedRecognizer | None = None,
    sink: RecordingSink | None = None,
    preferences: Any = None,
    coordinator: Any = None,
    journal: Any = None,
    observe: bool = True,
) -> WorkerHarness:
    """A worker over scripted collaborators, policy already observed capable."""
    from companion.speech.capture import CaptureRouter
    from companion.speech.confirmation import ConfirmationLedger
    from companion.speech.coordination import VoiceOutputCoordinator
    from companion.speech.indicator import ListeningIndicator
    from companion.speech.policy import (
        SpeechInputPolicy,
        SpeechInputPreferences,
        SpeechInputSignals,
    )
    from companion.speech.worker import CaptureWorker

    backend = backend or ScriptedCaptureBackend()
    recognizer = recognizer or ScriptedRecognizer()
    sink = sink or RecordingSink()
    router = CaptureRouter([backend])
    registry = scripted_registry(recognizer)
    policy = SpeechInputPolicy(preferences or SpeechInputPreferences())
    if observe:
        policy.observe(SpeechInputSignals(
            capture_device_available=True,
            recognizer_available=True,
            streaming_recognizer_available=recognizer.declaration.supports_streaming,
        ))
    indicator = ListeningIndicator()
    indicator.attach(sink)
    ledger = ConfirmationLedger()
    coordinator = coordinator or VoiceOutputCoordinator(None)
    worker = CaptureWorker(
        router=router,
        registry=registry,
        policy=policy,
        indicator=indicator,
        ledger=ledger,
        coordinator=coordinator,
        journal=journal,
    )
    return WorkerHarness(
        worker=worker, backend=backend, recognizer=recognizer, router=router,
        policy=policy, indicator=indicator, ledger=ledger, sink=sink,
        journal=journal, coordinator=coordinator,
    )
