// SPDX-FileCopyrightText: 2026 ComradeArt
// SPDX-License-Identifier: GPL-3.0-or-later
//
// A resolved theme, rendered as St CSS.
//
// St's stylesheet language is a subset of CSS: no custom properties, no calc(),
// no flexbox, no media queries, no `:not()`, and no `var()`. That is why this is
// a function rather than a file. Everything the missing features would have done
// — a second palette, a scale factor, a contrast mode — happens in JavaScript
// before a single declaration is written, and what St receives is a flat sheet
// of literals it can parse.
//
// This module imports nothing and touches nothing. It takes a theme object and
// returns a string, so tests/shell/test_design_stylesheet.py can render all four
// themes at all four scales under node and assert on the text: that no
// `font-size` is absolute in the sense of being the same at 100 % and 200 %,
// that every reactive class has a `:focus` rule, and that the high-contrast
// sheet differs from the default one in more than a handful of bytes. Those are
// the three claims the accessibility run measured and disproved.
//
// ## The one rule about writing rules here
//
// Never write a literal. If a value is not `theme.something`, it is a value that
// cannot respond to a setting, and the whole failure this phase exists to fix
// was 43 font sizes and 151 colours that could not respond to a setting. The
// only exceptions are structural constants with no visual meaning — `1px` for a
// hairline divider's height, `0` — and `none`.

/** Every class that takes pointer or keyboard input, and therefore needs a focus rule. */
export const REACTIVE_CLASSES = [
    'bunny-shell-status', 'bunny-top-identity', 'bunny-top-indicator-icon', 'bunny-top-battery',
    'bunny-top-clock-box', 'bunny-top-avatar', 'bunny-search-entry', 'bunny-sidebar-row',
    'bunny-power-row', 'bunny-dock-tile', 'bunny-card-action', 'bunny-quick-tile',
    'bunny-media-button', 'bunny-agenda-row', 'bunny-assistant-entry',
    'bunny-assistant-icon-button', 'bunny-assistant-file-action', 'bunny-bubble-more',
    'bunny-suggestion-row', 'bunny-suggestions-more', 'bunny-search-row', 'bunny-toast',
    'bunny-trust-action', 'bunny-trust-disclosure', 'bunny-result-action', 'bunny-error-action',
    'bunny-capsule-disclosure',
];

const px = value => `${Math.round(value)}px`;

/**
 * `font-size`, `font-weight` and, for the monospace role, a family.
 *
 * Written from `theme.type[role]` so that the size at 150 % is 150 % of the size
 * at 100 % by construction rather than by a second table someone has to keep in
 * step.
 */
function type(theme, role) {
    const spec = theme.type[role];
    const family = spec.family === 'monospace' ? ' font-family: monospace;' : '';
    return `font-size: ${px(spec.size)}; font-weight: ${spec.weight};${family}`;
}

/** The one focus treatment. §13: identical everywhere, thicker at high contrast. */
function focusRule(selector, theme, {inset = false} = {}) {
    const offset = inset ? theme.focus.insetOffset : theme.focus.offset;
    return `${selector}:focus { outline: ${px(theme.focus.width)} solid ${theme.focus.colour}; outline-offset: ${px(offset)}; }`;
}

/**
 * Render the whole desktop stylesheet.
 *
 * @param {object} theme from resolveTheme()
 * @returns {string} St-parseable CSS
 */
export function renderStylesheet(theme) {
    const c = theme.colour;
    const s = theme.space;
    const r = theme.radius;
    const m = theme.metric;
    const i = theme.icon;
    const out = [];
    const rule = text => out.push(text);
    const focus = (selector, options) => out.push(focusRule(selector, theme, options));

    rule(`/* Generated by lib/design/stylesheet.js. Theme ${theme.name}, text scale ${theme.textScale}.`);
    rule(` * Do not edit: this file is written at runtime and replaced whenever a`);
    rule(` * display setting changes. Edit lib/design/tokens.js instead. */`);

    // ------------------------------------------------------------ indicator
    rule(`.bunny-shell-icon { color: ${c.accentText}; }`);
    rule(`.bunny-shell-status { color: ${c.textSecondary}; ${type(theme, 'bodySmall')} }`);
    focus('.bunny-shell-status');

    // ------------------------------------------------------------- surfaces
    rule(`.bunny-wallpaper-fallback {
  background-gradient-direction: vertical;
  background-gradient-start: ${c.wallpaperStart};
  background-gradient-end: ${c.wallpaperEnd};
}`);

    // Every panel shares one surface treatment. At high contrast the shadow is
    // gone and the border carries the separation instead, because a shadow is
    // precisely the cue a high-contrast theme exists to stop relying on.
    const panelBorder = theme.highContrast ? c.borderStrong : c.border;
    rule(`.bunny-card,
.bunny-top-bar,
.bunny-sidebar,
.bunny-dock,
.bunny-bubble,
.bunny-suggestions,
.bunny-search-results,
.bunny-power-menu,
.bunny-toast,
.bunny-trust,
.bunny-result,
.bunny-error,
.bunny-capsule {
  background-color: ${c.surfaceSecondary};
  border: 1px solid ${panelBorder};
  color: ${c.textPrimary};
  box-shadow: ${theme.shadow.raised};
}`);

    rule(`.bunny-card { border-radius: ${px(r.card)}; padding: 0; }`);
    rule(`.bunny-top-bar { border-radius: 0 0 ${px(r.panel)} ${px(r.panel)}; border-top-width: 0; }`);
    rule(`.bunny-sidebar { border-radius: ${px(r.panel)}; }`);
    rule(`.bunny-dock { border-radius: ${px(r.panel)}; }`);
    rule(`.bunny-bubble { border-radius: ${px(r.floating)}; }`);
    rule(`.bunny-suggestions { border-radius: ${px(r.floating)}; }`);
    rule(`.bunny-search-results { border-radius: ${px(r.card)}; }`);
    rule(`.bunny-power-menu { border-radius: ${px(r.card)}; box-shadow: ${theme.shadow.overlay}; }`);
    rule(`.bunny-toast { border-radius: ${px(r.control)}; }`);

    // ------------------------------------------------------------- top bar
    rule(`.bunny-top-bar-row { padding: 0 ${px(s.md)}; spacing: ${px(s.md)}; height: ${px(m.topBarHeight)}; }`);
    rule(`.bunny-top-identity { spacing: ${px(s.sm)}; padding: ${px(s.xs)} ${px(s.sm)}; border-radius: ${px(r.control)}; }`);
    rule(`.bunny-top-identity:hover { background-color: ${c.surfaceHover}; }`);
    focus('.bunny-top-identity');
    rule(`.bunny-top-logo { color: ${c.accentText}; }`);
    rule(`.bunny-top-wordmark { ${type(theme, 'heading')} color: ${c.textPrimary}; }`);

    rule(`.bunny-search-wrapper { min-width: ${px(m.searchWidth)}; }`);
    rule(`.bunny-search-entry {
  background-color: ${c.surfaceRaised};
  border: 1px solid ${c.borderStrong};
  border-radius: ${px(r.control)};
  color: ${c.textPrimary};
  padding: ${px(s.xs)} ${px(s.md)};
  min-width: ${px(m.searchWidth)};
  ${type(theme, 'body')}
}`);
    rule(`.bunny-search-entry:focus { border-color: ${c.focus}; background-color: ${c.surfaceOverlay}; }`);
    rule(`.bunny-search-entry StLabel.hint-text { color: ${c.textMuted}; }`);
    rule(`.bunny-search-icon { color: ${c.textSecondary}; }`);

    rule(`.bunny-top-indicators { spacing: ${px(s.md)}; }`);
    rule(`.bunny-microphone-indicator {
  spacing: ${px(s.xs)};
  padding: ${px(s.xs)} ${px(s.sm)};
  border-radius: ${px(r.control)};
  background-color: ${c.surfaceRaised};
  border: 1px solid ${c.danger};
}`);
    rule(`.bunny-microphone-indicator-icon, .bunny-microphone-indicator-label { color: ${c.danger}; }`);
    rule(`.bunny-microphone-indicator-label { ${type(theme, 'caption')} }`);

    rule(`.bunny-top-indicator-icon { color: ${c.textSecondary}; padding: ${px(s.xs)}; border-radius: ${px(s.sm)}; icon-size: ${px(i.medium)}; }`);
    rule(`.bunny-top-indicator-icon:hover { color: ${c.textPrimary}; background-color: ${c.surfaceHover}; }`);
    focus('.bunny-top-indicator-icon');

    rule(`.bunny-top-battery { spacing: ${px(s.xs)}; padding: ${px(s.xxs)} ${px(s.sm)}; border-radius: ${px(s.sm)}; }`);
    rule(`.bunny-top-battery:hover { background-color: ${c.surfaceHover}; }`);
    focus('.bunny-top-battery');
    rule(`.bunny-top-battery-label { ${type(theme, 'caption')} color: ${c.textSecondary}; }`);

    rule(`.bunny-top-clock-box { padding: ${px(s.xxs)} ${px(s.sm)}; border-radius: ${px(s.sm)}; }`);
    rule(`.bunny-top-clock-box:hover { background-color: ${c.surfaceHover}; }`);
    focus('.bunny-top-clock-box');
    rule(`.bunny-top-clock { ${type(theme, 'heading')} color: ${c.textPrimary}; }`);
    rule(`.bunny-top-date { ${type(theme, 'caption')} color: ${c.textSecondary}; }`);

    // The avatar is a filled circle carrying initials, so its text is on the
    // accent rather than on a surface and takes the textOnAccent role.
    const avatar = Math.round(theme.type.button.size * 2.4);
    rule(`.bunny-top-avatar {
  background-color: ${c.accent};
  color: ${c.textOnAccent};
  ${type(theme, 'button')}
  border-radius: ${px(avatar / 2)};
  width: ${px(avatar)};
  height: ${px(avatar)};
  text-align: center;
  padding-top: ${px((avatar - theme.type.button.size) / 2 - 1)};
}`);
    focus('.bunny-top-avatar');

    // ------------------------------------------------------------- sidebar
    rule(`.bunny-sidebar-column { padding: ${px(s.md)} ${px(s.sm)}; spacing: ${px(s.xxs)}; }`);
    rule(`.bunny-sidebar-row { spacing: ${px(s.md)}; padding: ${px(s.sm)} ${px(s.md)}; border-radius: ${px(r.control)}; color: ${c.textSecondary}; }`);
    rule(`.bunny-sidebar-row:hover { background-color: ${c.surfaceHover}; color: ${c.textPrimary}; }`);
    focus('.bunny-sidebar-row', {inset: true});
    rule(`.bunny-sidebar-row-selected {
  background-color: ${c.selection};
  color: ${c.textOnSelection};
  font-weight: 600;
  border-left: ${px(theme.focus.width + 1)} solid ${c.accentText};
  padding-left: ${px(s.md - theme.focus.width - 1)};
}`);
    rule(`.bunny-sidebar-icon { icon-size: ${px(i.medium)}; }`);
    rule(`.bunny-sidebar-label { ${type(theme, 'body')} }`);
    rule(`.bunny-sidebar-collapsed .bunny-sidebar-row { padding: ${px(s.sm)}; }`);
    rule(`.bunny-sidebar-divider { height: 1px; background-color: ${c.border}; margin: ${px(s.sm)} ${px(s.xs)}; }`);
    rule(`.bunny-sidebar-power { color: ${c.danger}; }`);
    rule(`.bunny-sidebar-power:hover { background-color: ${c.surfaceActive}; color: ${c.textPrimary}; }`);

    rule(`.bunny-power-column { padding: ${px(s.sm)}; spacing: ${px(s.xxs)}; }`);
    rule(`.bunny-power-row { spacing: ${px(s.md)}; padding: ${px(s.sm)} ${px(s.md)}; border-radius: ${px(r.control)}; color: ${c.textPrimary}; }`);
    rule(`.bunny-power-row:hover { background-color: ${c.surfaceHover}; }`);
    focus('.bunny-power-row', {inset: true});

    // ---------------------------------------------------------------- dock
    rule(`.bunny-dock-row { padding: ${px(s.sm)} ${px(s.md)}; spacing: ${px(s.sm)}; }`);
    rule(`.bunny-dock-tile { padding: ${px(s.xs)}; border-radius: ${px(r.control)}; width: ${px(m.dockIcon)}; height: ${px(m.dockIcon)}; }`);
    rule(`.bunny-dock-tile:hover { background-color: ${c.surfaceHover}; }`);
    focus('.bunny-dock-tile');
    const dot = Math.max(6, Math.round(theme.type.caption.size * 0.6));
    rule(`.bunny-dock-running {
  width: ${px(dot)};
  height: ${px(dot)};
  border-radius: ${px(dot / 2)};
  background-color: ${c.accentText};
  margin-top: ${px(s.xxs)};
}`);

    // --------------------------------------------------------------- cards
    rule(`.bunny-card-content { padding: ${px(s.md)} ${px(s.md)}; spacing: ${px(s.sm)}; }`);
    rule(`.bunny-card-header { spacing: ${px(s.sm)}; }`);
    rule(`.bunny-card-title { ${type(theme, 'caption')} color: ${c.textSecondary}; text-transform: uppercase; }`);
    rule(`.bunny-card-action {
  ${type(theme, 'caption')}
  color: ${c.accentText};
  background-color: ${c.accentSoft};
  border-radius: ${px(s.sm)};
  padding: ${px(s.xxs)} ${px(s.sm)};
  border: none;
}`);
    rule(`.bunny-card-action:hover { background-color: ${c.selection}; color: ${c.textOnSelection}; }`);
    focus('.bunny-card-action');

    rule(`.bunny-metric-row { spacing: ${px(s.sm)}; padding: ${px(s.xxs)} 0; }`);
    rule(`.bunny-metric-name { ${type(theme, 'bodySmall')} color: ${c.textSecondary}; }`);
    rule(`.bunny-metric-value { ${type(theme, 'bodySmall')} font-weight: 600; color: ${c.textPrimary}; }`);
    rule(`.bunny-metric-unavailable { color: ${c.textMuted}; font-weight: 400; font-style: italic; }`);
    rule(`.bunny-meter { background-color: ${c.surfaceHover}; border-radius: ${px(s.xxs)}; }`);
    rule(`.bunny-meter-fill { border-radius: ${px(s.xxs)}; }`);
    rule(`.bunny-meter-unavailable { background-color: ${c.surfaceHover}; }`);

    rule(`.bunny-overview-body { spacing: ${px(s.md)}; }`);
    rule(`.bunny-dial-column { spacing: ${px(s.xs)}; }`);
    rule(`.bunny-dial-caption { ${type(theme, 'caption')} color: ${c.textSecondary}; text-align: center; }`);
    rule(`.bunny-dial-value { ${type(theme, 'title')} color: ${c.textPrimary}; }`);
    rule(`.bunny-dial-value-unavailable { ${type(theme, 'caption')} font-weight: 400; color: ${c.textMuted}; }`);
    rule(`.bunny-overview-rows { spacing: ${px(s.sm)}; }`);
    rule(`.bunny-overview-body-stacked { spacing: ${px(s.sm)}; }`);
    rule(`.bunny-overview-body-stacked .bunny-dial-column { padding-bottom: ${px(s.xxs)}; }`);

    rule(`.bunny-quick-grid { spacing: ${px(m.quickTileGap)}; }`);
    rule(`.bunny-quick-tile { padding: ${px(s.sm)} ${px(s.xs)}; border-radius: ${px(r.control)}; width: ${px(m.quickTileWidth)}; spacing: ${px(s.xs)}; }`);
    rule(`.bunny-quick-tile:hover { background-color: ${c.surfaceHover}; }`);
    focus('.bunny-quick-tile', {inset: true});
    rule(`.bunny-tile-label { ${type(theme, 'caption')} color: ${c.textSecondary}; text-align: center; }`);
    rule(`.bunny-quick-empty { ${type(theme, 'bodySmall')} color: ${c.textMuted}; padding: ${px(s.sm)} ${px(s.xxs)}; }`);
    rule(`.bunny-unavailable { opacity: 0.38; }`);

    rule(`.bunny-media-row { spacing: ${px(s.sm)}; }`);
    rule(`.bunny-media-art { border-radius: ${px(s.sm)}; }`);
    rule(`.bunny-media-text { spacing: 1px; }`);
    rule(`.bunny-media-title { ${type(theme, 'body')} font-weight: 600; color: ${c.textPrimary}; }`);
    rule(`.bunny-media-artist { ${type(theme, 'caption')} color: ${c.textSecondary}; }`);
    rule(`.bunny-media-controls { spacing: ${px(s.xs)}; }`);
    rule(`.bunny-media-button { padding: ${px(s.xs)}; border-radius: ${px(s.sm)}; color: ${c.textSecondary}; }`);
    rule(`.bunny-media-button:hover { background-color: ${c.surfaceHover}; color: ${c.textPrimary}; }`);
    focus('.bunny-media-button');
    rule(`.bunny-media-time { ${type(theme, 'caption')} color: ${c.textMuted}; }`);

    rule(`.bunny-agenda-list { spacing: ${px(s.xs)}; }`);
    rule(`.bunny-agenda-row { spacing: ${px(s.sm)}; padding: ${px(s.xs)} ${px(s.sm)}; border-radius: ${px(s.sm)}; }`);
    rule(`.bunny-agenda-row:hover { background-color: ${c.surfaceHover}; }`);
    focus('.bunny-agenda-row', {inset: true});
    rule(`.bunny-agenda-row-past { opacity: 0.5; }`);
    rule(`.bunny-agenda-time { ${type(theme, 'caption')} font-weight: 600; color: ${c.accentText}; }`);
    rule(`.bunny-agenda-summary { ${type(theme, 'bodySmall')} color: ${c.textPrimary}; }`);
    rule(`.bunny-agenda-empty { spacing: ${px(s.xxs)}; padding: ${px(s.xs)} ${px(s.xxs)}; }`);
    rule(`.bunny-agenda-empty-primary { ${type(theme, 'body')} color: ${c.textPrimary}; }`);
    rule(`.bunny-agenda-empty-secondary { ${type(theme, 'caption')} color: ${c.textMuted}; }`);
    rule(`.bunny-agenda-more { ${type(theme, 'caption')} color: ${c.textSecondary}; padding-left: ${px(s.sm)}; }`);

    rule(`.bunny-monitor-rates { spacing: ${px(s.xs)}; }`);
    rule(`.bunny-monitor-up { ${type(theme, 'bodySmall')} font-weight: 600; color: ${c.success}; }`);
    rule(`.bunny-monitor-down { ${type(theme, 'bodySmall')} font-weight: 600; color: ${c.accentText}; }`);
    rule(`.bunny-monitor-arrow-up { icon-size: ${px(i.small)}; color: ${c.success}; }`);
    rule(`.bunny-monitor-arrow-down { icon-size: ${px(i.small)}; color: ${c.accentText}; }`);
    rule(`.bunny-monitor-graph { border-radius: ${px(s.sm)}; background-color: ${c.surfaceHover}; }`);

    // ----------------------------------------------------------- assistant
    rule(`.bunny-assistant-scroll { max-height: ${px(theme.type.body.size * 9)}; }`);
    rule(`.bunny-assistant-transcript { spacing: ${px(s.xs)}; padding-right: ${px(s.xs)}; }`);
    rule(`.bunny-turn { padding: ${px(s.xs)} ${px(s.sm)}; border-radius: ${px(r.control)}; max-width: ${px(m.turnMaxWidth)}; }`);
    rule(`.bunny-turn-user { background-color: ${c.selection}; }`);
    rule(`.bunny-turn-user .bunny-turn-text { color: ${c.textOnSelection}; }`);
    rule(`.bunny-turn-bunny { background-color: ${c.surfaceRaised}; }`);
    rule(`.bunny-turn-error { background-color: ${c.surfaceRaised}; border: 1px solid ${c.danger}; }`);
    rule(`.bunny-turn-text { ${type(theme, 'bodySmall')} color: ${c.textPrimary}; }`);
    rule(`.bunny-assistant-status { ${type(theme, 'caption')} color: ${c.textSecondary}; font-style: italic; }`);
    rule(`.bunny-assistant-status-error { color: ${c.danger}; font-style: normal; }`);
    rule(`.bunny-assistant-busy .bunny-assistant-entry { opacity: 0.6; }`);
    rule(`.bunny-assistant-input-row { spacing: ${px(s.xs)}; }`);
    rule(`.bunny-assistant-entry {
  background-color: ${c.surfaceRaised};
  border: 1px solid ${c.borderStrong};
  border-radius: ${px(r.control)};
  color: ${c.textPrimary};
  padding: ${px(s.xs)} ${px(s.sm)};
  ${type(theme, 'bodySmall')}
}`);
    rule(`.bunny-assistant-entry:focus { border-color: ${c.focus}; }`);
    rule(`.bunny-assistant-entry StLabel.hint-text { color: ${c.textMuted}; }`);
    rule(`.bunny-assistant-icon-button { padding: ${px(s.xs)}; border-radius: ${px(r.control)}; color: ${c.textSecondary}; }`);
    rule(`.bunny-assistant-icon-button:hover { background-color: ${c.selection}; color: ${c.textOnSelection}; }`);
    focus('.bunny-assistant-icon-button');
    rule(`.bunny-assistant-microphone-active { color: ${c.textPrimary}; background-color: ${c.surfaceActive}; border: 1px solid ${c.danger}; }`);
    rule(`.bunny-assistant-file-results-scroll { max-height: ${px(theme.type.body.size * 11)}; }`);
    rule(`.bunny-assistant-file-results { spacing: ${px(s.xs)}; padding-right: ${px(s.xs)}; }`);
    rule(`.bunny-assistant-file-result { spacing: ${px(s.xs)}; padding: ${px(s.xs)} ${px(s.sm)}; border-radius: ${px(s.sm)}; background-color: ${c.surfaceRaised}; }`);
    rule(`.bunny-assistant-file-title { ${type(theme, 'caption')} color: ${c.textPrimary}; }`);
    rule(`.bunny-assistant-file-location { ${type(theme, 'caption')} font-weight: 400; color: ${c.textMuted}; }`);
    rule(`.bunny-assistant-file-action { padding: ${px(s.xs)} ${px(s.xs)}; border-radius: ${px(s.sm)}; color: ${c.accentText}; ${type(theme, 'caption')} }`);
    rule(`.bunny-assistant-file-action:hover { background-color: ${c.selection}; color: ${c.textOnSelection}; }`);
    focus('.bunny-assistant-file-action');

    // ------------------------------------------------- character and bubbles
    rule(`.bunny-greeting { padding: ${px(s.xs)} ${px(s.sm)}; spacing: ${px(s.xxs)}; }`);
    rule(`.bunny-greeting-primary { ${type(theme, 'display')} color: ${c.textPrimary}; }`);
    rule(`.bunny-greeting-secondary { ${type(theme, 'heading')} font-weight: 400; color: ${c.textSecondary}; }`);
    rule(`.bunny-bubble-column { padding: ${px(s.md)} ${px(s.md)}; spacing: ${px(s.sm)}; }`);
    rule(`.bunny-bubble-text { ${type(theme, 'body')} color: ${c.textPrimary}; }`);
    rule(`.bunny-bubble-more { ${type(theme, 'caption')} color: ${c.accentText}; background-color: ${c.accentSoft}; border-radius: ${px(s.sm)}; padding: ${px(s.xs)} ${px(s.sm)}; border: none; }`);
    rule(`.bunny-bubble-more:hover { background-color: ${c.selection}; color: ${c.textOnSelection}; }`);
    focus('.bunny-bubble-more');
    rule(`.bunny-bubble-warning { border-color: ${c.warning}; }`);
    rule(`.bunny-bubble-error { border-color: ${c.danger}; }`);

    rule(`.bunny-suggestions-column { padding: ${px(s.md)} ${px(s.md)}; spacing: ${px(s.xxs)}; }`);
    rule(`.bunny-suggestion-row { spacing: ${px(s.sm)}; padding: ${px(s.xs)} ${px(s.sm)}; border-radius: ${px(r.control)}; }`);
    rule(`.bunny-suggestion-row:hover { background-color: ${c.surfaceHover}; }`);
    focus('.bunny-suggestion-row', {inset: true});
    rule(`.bunny-suggestion-glyph { icon-size: ${px(i.small)}; color: ${c.accentText}; }`);
    rule(`.bunny-suggestion-label { ${type(theme, 'bodySmall')} color: ${c.textPrimary}; }`);
    rule(`.bunny-suggestions-more { ${type(theme, 'caption')} color: ${c.accentText}; padding: ${px(s.xs)} ${px(s.sm)}; border-radius: ${px(s.sm)}; }`);
    rule(`.bunny-suggestions-more:hover { background-color: ${c.accentSoft}; }`);
    focus('.bunny-suggestions-more', {inset: true});

    // ------------------------------------------------------- search results
    rule(`.bunny-search-list { padding: ${px(s.xs)}; spacing: ${px(s.xxs)}; }`);
    rule(`.bunny-search-row { spacing: ${px(s.sm)}; padding: ${px(s.xs)} ${px(s.sm)}; border-radius: ${px(s.sm)}; }`);
    rule(`.bunny-search-row:hover { background-color: ${c.surfaceHover}; }`);
    focus('.bunny-search-row', {inset: true});
    rule(`.bunny-search-row-icon { color: ${c.textSecondary}; }`);
    rule(`.bunny-search-row-title { ${type(theme, 'body')} color: ${c.textPrimary}; }`);
    rule(`.bunny-search-row-subtitle { ${type(theme, 'caption')} color: ${c.textMuted}; }`);

    // --------------------------------------------------------- notifications
    rule(`.bunny-notification-layer { spacing: ${px(s.sm)}; }`);
    rule(`.bunny-toast-row { spacing: ${px(s.sm)}; padding: ${px(s.sm)} ${px(s.md)}; }`);
    rule(`.bunny-toast-text { ${type(theme, 'bodySmall')} color: ${c.textPrimary}; }`);
    rule(`.bunny-toast-icon { color: ${c.textSecondary}; icon-size: ${px(i.medium)}; }`);
    // Severity is carried by the icon and the leading word as well as by this
    // border. §19: a coloured stripe on its own is colour alone.
    rule(`.bunny-toast-info { border-left: ${px(theme.focus.width + 1)} solid ${c.accentText}; }`);
    rule(`.bunny-toast-warning { border-left: ${px(theme.focus.width + 1)} solid ${c.warning}; }`);
    rule(`.bunny-toast-error { border-left: ${px(theme.focus.width + 1)} solid ${c.danger}; }`);
    rule(`.bunny-toast-severity { ${type(theme, 'caption')} font-weight: 700; text-transform: uppercase; }`);
    rule(`.bunny-toast-severity-info { color: ${c.accentText}; }`);
    rule(`.bunny-toast-severity-warning { color: ${c.warning}; }`);
    rule(`.bunny-toast-severity-error { color: ${c.danger}; }`);
    rule(`.bunny-toast:hover { background-color: ${c.surfaceOverlay}; }`);
    focus('.bunny-toast');

    out.push(renderComponents(theme));
    return out.join('\n');
}

/**
 * The design-system components: Trust, task status, result, error, capsule.
 *
 * Split out only for length. They render from the same theme and follow the
 * same rule about literals.
 */
function renderComponents(theme) {
    const c = theme.colour;
    const s = theme.space;
    const r = theme.radius;
    const out = [];
    const rule = text => out.push(text);
    const focus = (selector, options) => out.push(focusRule(selector, theme, options));

    // -------------------------------------------------------------- Trust
    // The one surface permitted to interrupt, and therefore the only one at
    // dialog elevation.
    rule(`.bunny-trust { border-radius: ${px(r.modal)}; box-shadow: ${theme.shadow.dialog}; border: ${px(theme.highContrast ? theme.focus.width : 1)} solid ${theme.highContrast ? c.borderStrong : c.trust}; }`);
    rule(`.bunny-trust-column { padding: ${px(s.lg)}; spacing: ${px(s.md)}; }`);
    rule(`.bunny-trust-scrim { background-color: ${c.scrim}; }`);
    rule(`.bunny-trust-heading { ${type(theme, 'title')} color: ${c.textPrimary}; }`);
    rule(`.bunny-trust-subheading { ${type(theme, 'caption')} color: ${c.textSecondary}; text-transform: uppercase; }`);
    rule(`.bunny-trust-identity { spacing: ${px(s.sm)}; padding: ${px(s.sm)} ${px(s.md)}; border-radius: ${px(r.control)}; background-color: ${c.surfaceRaised}; }`);
    rule(`.bunny-trust-identity-name { ${type(theme, 'body')} font-weight: 600; color: ${c.textPrimary}; }`);
    rule(`.bunny-trust-identity-origin { ${type(theme, 'caption')} color: ${c.textMuted}; }`);
    rule(`.bunny-trust-body { spacing: ${px(s.sm)}; }`);
    rule(`.bunny-trust-line-strong { ${type(theme, 'body')} font-weight: 600; color: ${c.textPrimary}; }`);
    rule(`.bunny-trust-line-normal { ${type(theme, 'body')} color: ${c.textPrimary}; }`);
    rule(`.bunny-trust-line-quiet { ${type(theme, 'bodySmall')} color: ${c.textSecondary}; }`);
    rule(`.bunny-trust-line-warning { ${type(theme, 'bodySmall')} font-weight: 600; color: ${c.warning}; }`);
    // The risk marker is a glyph, not a tint. §19.
    rule(`.bunny-trust-risk { spacing: ${px(s.xs)}; }`);
    rule(`.bunny-trust-risk-glyph { icon-size: ${px(theme.icon.medium)}; }`);
    rule(`.bunny-trust-risk-label { ${type(theme, 'caption')} font-weight: 700; text-transform: uppercase; }`);
    rule(`.bunny-trust-risk-accent .bunny-trust-risk-glyph, .bunny-trust-risk-accent .bunny-trust-risk-label { color: ${c.trust}; }`);
    rule(`.bunny-trust-risk-warning .bunny-trust-risk-glyph, .bunny-trust-risk-warning .bunny-trust-risk-label { color: ${c.warning}; }`);
    rule(`.bunny-trust-risk-danger .bunny-trust-risk-glyph, .bunny-trust-risk-danger .bunny-trust-risk-label { color: ${c.danger}; }`);
    rule(`.bunny-trust-actions { spacing: ${px(s.sm)}; padding-top: ${px(s.xs)}; }`);
    // Touch targets. §35: the two controls that decide a permission are the
    // last place to optimise for pointer precision.
    const target = Math.max(34, Math.round(theme.type.button.size * 3));
    rule(`.bunny-trust-action {
  ${type(theme, 'button')}
  padding: ${px(s.sm)} ${px(s.lg)};
  min-width: ${px(target * 3)};
  height: ${px(target)};
  border-radius: ${px(r.control)};
  border: 1px solid ${c.borderStrong};
  background-color: ${c.surfaceRaised};
  color: ${c.textPrimary};
}`);
    rule(`.bunny-trust-action:hover { background-color: ${c.surfaceHover}; }`);
    focus('.bunny-trust-action');
    rule(`.bunny-trust-action-safe { border-color: ${c.borderStrong}; font-weight: 700; }`);
    rule(`.bunny-trust-action-allow { border-color: ${c.trust}; }`);
    rule(`.bunny-trust-disclosure { ${type(theme, 'caption')} color: ${c.accentText}; padding: ${px(s.xs)} ${px(s.sm)}; border-radius: ${px(s.sm)}; }`);
    rule(`.bunny-trust-disclosure:hover { background-color: ${c.accentSoft}; }`);
    focus('.bunny-trust-disclosure');
    rule(`.bunny-trust-details { spacing: ${px(s.xs)}; padding: ${px(s.sm)} ${px(s.md)}; border-radius: ${px(s.sm)}; background-color: ${c.surfaceRaised}; }`);
    rule(`.bunny-trust-detail { ${type(theme, 'mono')} color: ${c.textSecondary}; }`);

    // ------------------------------------------------------- security state
    // Every standing is an icon, a word and a colour. Removing any one of the
    // three still leaves the state readable, which is the §19 requirement.
    rule(`.bunny-standing { spacing: ${px(s.xs)}; padding: ${px(s.xxs)} ${px(s.sm)}; border-radius: ${px(s.sm)}; border: 1px solid ${c.border}; }`);
    rule(`.bunny-standing-glyph { icon-size: ${px(theme.icon.small)}; }`);
    rule(`.bunny-standing-label { ${type(theme, 'caption')} font-weight: 600; }`);
    rule(`.bunny-standing-granted .bunny-standing-glyph, .bunny-standing-granted .bunny-standing-label { color: ${c.success}; }`);
    rule(`.bunny-standing-denied .bunny-standing-glyph, .bunny-standing-denied .bunny-standing-label { color: ${c.textSecondary}; }`);
    rule(`.bunny-standing-blocked .bunny-standing-glyph, .bunny-standing-blocked .bunny-standing-label { color: ${c.blocked}; }`);
    rule(`.bunny-standing-unenforced { border-color: ${c.warning}; }`);
    rule(`.bunny-standing-unenforced .bunny-standing-glyph, .bunny-standing-unenforced .bunny-standing-label { color: ${c.warning}; }`);
    rule(`.bunny-standing-unavailable .bunny-standing-glyph, .bunny-standing-unavailable .bunny-standing-label { color: ${c.textMuted}; }`);

    // ---------------------------------------------------------- task status
    rule(`.bunny-task { spacing: ${px(s.sm)}; }`);
    rule(`.bunny-task-row { spacing: ${px(s.sm)}; }`);
    rule(`.bunny-task-glyph { icon-size: ${px(theme.icon.medium)}; }`);
    rule(`.bunny-task-label { ${type(theme, 'body')} color: ${c.textPrimary}; }`);
    rule(`.bunny-task-detail { ${type(theme, 'caption')} color: ${c.textSecondary}; }`);
    rule(`.bunny-task-waiting .bunny-task-glyph { color: ${c.textSecondary}; }`);
    rule(`.bunny-task-approval .bunny-task-glyph { color: ${c.warning}; }`);
    rule(`.bunny-task-working .bunny-task-glyph { color: ${c.accentText}; }`);
    rule(`.bunny-task-completed .bunny-task-glyph { color: ${c.success}; }`);
    rule(`.bunny-task-blocked .bunny-task-glyph { color: ${c.blocked}; }`);
    rule(`.bunny-task-failed .bunny-task-glyph { color: ${c.danger}; }`);
    rule(`.bunny-task-cancelled .bunny-task-glyph { color: ${c.textMuted}; }`);
    // Stage progress, not a fabricated percentage. §21.
    rule(`.bunny-task-stages { spacing: ${px(s.xs)}; }`);
    rule(`.bunny-task-stage { ${type(theme, 'caption')} color: ${c.textMuted}; }`);
    rule(`.bunny-task-stage-done { color: ${c.textSecondary}; }`);
    rule(`.bunny-task-stage-current { color: ${c.textPrimary}; font-weight: 600; }`);

    // --------------------------------------------------------------- result
    rule(`.bunny-result { border-radius: ${px(r.card)}; }`);
    rule(`.bunny-result-column { padding: ${px(s.md)}; spacing: ${px(s.sm)}; }`);
    rule(`.bunny-result-heading { ${type(theme, 'heading')} color: ${c.textPrimary}; }`);
    rule(`.bunny-result-filename { ${type(theme, 'body')} font-weight: 600; color: ${c.textPrimary}; }`);
    rule(`.bunny-result-kind { ${type(theme, 'caption')} color: ${c.textMuted}; }`);
    rule(`.bunny-result-preview { border-radius: ${px(s.sm)}; border: 1px solid ${c.border}; }`);
    rule(`.bunny-result-actions { spacing: ${px(s.sm)}; }`);
    rule(`.bunny-result-action { ${type(theme, 'button')} padding: ${px(s.xs)} ${px(s.md)}; border-radius: ${px(s.sm)}; background-color: ${c.accentSoft}; color: ${c.accentText}; }`);
    rule(`.bunny-result-action:hover { background-color: ${c.selection}; color: ${c.textOnSelection}; }`);
    focus('.bunny-result-action');
    rule(`.bunny-result-provenance { ${type(theme, 'caption')} color: ${c.textMuted}; }`);

    // ---------------------------------------------------------------- error
    rule(`.bunny-error { border-radius: ${px(r.card)}; border-left: ${px(theme.focus.width + 1)} solid ${c.danger}; }`);
    rule(`.bunny-error-column { padding: ${px(s.md)}; spacing: ${px(s.sm)}; }`);
    rule(`.bunny-error-kind { ${type(theme, 'caption')} font-weight: 700; text-transform: uppercase; color: ${c.danger}; }`);
    rule(`.bunny-error-denied { border-left-color: ${c.textSecondary}; }`);
    rule(`.bunny-error-denied .bunny-error-kind { color: ${c.textSecondary}; }`);
    rule(`.bunny-error-blocked { border-left-color: ${c.blocked}; }`);
    rule(`.bunny-error-blocked .bunny-error-kind { color: ${c.blocked}; }`);
    rule(`.bunny-error-offline { border-left-color: ${c.warning}; }`);
    rule(`.bunny-error-offline .bunny-error-kind { color: ${c.warning}; }`);
    rule(`.bunny-error-headline { ${type(theme, 'body')} font-weight: 600; color: ${c.textPrimary}; }`);
    rule(`.bunny-error-explanation { ${type(theme, 'bodySmall')} color: ${c.textSecondary}; }`);
    rule(`.bunny-error-next { ${type(theme, 'bodySmall')} color: ${c.textPrimary}; }`);
    rule(`.bunny-error-action { ${type(theme, 'button')} padding: ${px(s.xs)} ${px(s.md)}; border-radius: ${px(s.sm)}; background-color: ${c.surfaceRaised}; color: ${c.textPrimary}; border: 1px solid ${c.borderStrong}; }`);
    focus('.bunny-error-action');

    // ------------------------------------------------------- protected space
    rule(`.bunny-capsule { border-radius: ${px(r.card)}; }`);
    rule(`.bunny-capsule-column { padding: ${px(s.md)}; spacing: ${px(s.sm)}; }`);
    rule(`.bunny-capsule-heading { ${type(theme, 'heading')} color: ${c.textPrimary}; }`);
    rule(`.bunny-capsule-row { spacing: ${px(s.sm)}; }`);
    rule(`.bunny-capsule-name { ${type(theme, 'bodySmall')} color: ${c.textSecondary}; }`);
    rule(`.bunny-capsule-value { ${type(theme, 'bodySmall')} font-weight: 600; color: ${c.textPrimary}; }`);
    rule(`.bunny-capsule-disclosure { ${type(theme, 'caption')} color: ${c.accentText}; padding: ${px(s.xs)} ${px(s.sm)}; border-radius: ${px(s.sm)}; }`);
    rule(`.bunny-capsule-disclosure:hover { background-color: ${c.accentSoft}; }`);
    focus('.bunny-capsule-disclosure');
    rule(`.bunny-capsule-detail { ${type(theme, 'mono')} color: ${c.textSecondary}; }`);

    return out.join('\n');
}
