#!/usr/bin/env python3
"""Generate the GNOME Shell stylesheet from Visual V2 tokens."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
TOKENS = ROOT / "visual-v2" / "tokens"
TARGET = ROOT / "shell" / "bunny-desktop-v2" / "stylesheet.css"
JS_TARGET = ROOT / "shell" / "bunny-desktop-v2" / "generatedTokens.js"


def read(name: str) -> dict:
    return json.loads((TOKENS / name).read_text(encoding="utf-8"))


def theme_block(name: str, colors: dict[str, str]) -> str:
    prefix = ".bunny-v2-root" if name == "dark" else f".bunny-v2-root.bunny-v2-{name.replace('highContrast', 'high-contrast')}"
    return f"""{prefix} {{ color: {colors['text']}; }}
{prefix} .bunny-v2-surface {{ background-color: {colors['surface']}; color: {colors['text']}; border: 1px solid {colors['border']}; }}
{prefix} .bunny-v2-panel {{ background-color: {colors['deep']}; color: {colors['text']}; border: 1px solid {colors['border']}; }}
{prefix} .bunny-v2-card {{ background-color: {colors['elevated']}; color: {colors['text']}; border: 1px solid {colors['border']}; }}
{prefix} .bunny-v2-muted {{ color: {colors['muted']}; }}
{prefix} .bunny-v2-subtle {{ color: {colors['subtle']}; }}
{prefix} .bunny-v2-focus:focus {{ border: 2px solid {colors['focus']}; }}"""


def render() -> str:
    colors = read("colors.json")
    spacing = read("spacing.json")["scale"]
    radii = read("radii.json")["tokens"]
    type_scale = read("typography.json")["scale"]
    motion = read("motion.json")["tokens"]
    elevation = read("elevation.json")["tokens"]
    semantic = colors["semantic"]
    blocks = [theme_block(name, values) for name, values in colors["themes"].items()]
    return """/* Generated by visual-v2/tools/generate_css.py. Do not hand edit. */
/* VISUAL PROTOTYPE ONLY — NOT RELEASE QUALIFIED — DO NOT MERGE INTO MAIN */

""" + "\n\n".join(blocks) + f"""

.bunny-v2-panel {{ border-radius: {radii['panel']}px; padding: {spacing['xl']}px; box-shadow: {elevation['panel']}; }}
.bunny-v2-card {{ border-radius: {radii['card']}px; padding: {spacing['lg']}px; }}
.bunny-v2-control {{ border-radius: {radii['control']}px; padding: {spacing['md']}px {spacing['lg']}px; }}
.bunny-v2-modal {{ border-radius: {radii['modal']}px; box-shadow: {elevation['modal']}; }}
.bunny-v2-title {{ font-family: 'Adwaita Sans'; font-size: {type_scale['title']['size']}px; font-weight: {type_scale['title']['weight']}; }}
.bunny-v2-heading {{ font-family: 'Adwaita Sans'; font-size: {type_scale['heading']['size']}px; font-weight: {type_scale['heading']['weight']}; }}
.bunny-v2-body {{ font-family: 'Adwaita Sans'; font-size: {type_scale['body']['size']}px; }}
.bunny-v2-label {{ font-family: 'Adwaita Sans'; font-size: {type_scale['label']['size']}px; font-weight: {type_scale['label']['weight']}; }}
.bunny-v2-caption {{ font-family: 'Adwaita Sans'; font-size: {type_scale['caption']['size']}px; }}
.bunny-v2-mono {{ font-family: 'Adwaita Mono'; font-size: {type_scale['monospace']['size']}px; }}
.bunny-v2-success {{ color: {semantic['success']}; }}
.bunny-v2-warning {{ color: {semantic['warning']}; }}
.bunny-v2-danger {{ color: {semantic['danger']}; }}
.bunny-v2-info {{ color: {semantic['info']}; }}
.bunny-v2-accent {{ color: {colors['accents']['violet']}; }}
.bunny-v2-sky {{ color: {colors['accents']['sky']}; }}
.bunny-v2-dock {{ border-radius: {radii['panel']}px; padding: {spacing['sm']}px {spacing['md']}px; spacing: {spacing['sm']}px; }}
.bunny-v2-dock-icon {{ border-radius: {radii['control']}px; padding: {spacing['sm']}px; min-width: 48px; min-height: 48px; }}
.bunny-v2-compact .bunny-v2-dock-icon {{ min-width: 38px; min-height: 38px; padding: {spacing['xs']}px; }}
.bunny-v2-quick-grid {{ spacing: {spacing['md']}px; }}
.bunny-v2-palette-result {{ border-radius: {radii['control']}px; padding: {spacing['md']}px; }}
.bunny-v2-mode-transition {{ transition-duration: {motion['mode']['milliseconds']}ms; }}
.bunny-v2-panel-transition {{ transition-duration: {motion['panel']['milliseconds']}ms; }}
.bunny-v2-reduced-motion, .bunny-v2-reduced-motion * {{ transition-duration: 0ms; transition-delay: 0ms; }}
.bunny-v2-mock-banner {{ background-color: {semantic['warning']}; color: #090C17; border-radius: {radii['small']}px; padding: {spacing['sm']}px {spacing['md']}px; font-weight: 700; }}
"""


def render_javascript() -> str:
    payload = {
        "spacing": read("spacing.json")["scale"],
        "radii": read("radii.json")["tokens"],
        "motion": {name: value["milliseconds"] for name, value in read("motion.json")["tokens"].items()},
        "opacity": read("opacity.json")["tokens"],
    }
    encoded = json.dumps(payload, indent=2, sort_keys=True)
    return (
        "// Generated by visual-v2/tools/generate_css.py. Do not hand edit.\n"
        "// VISUAL PROTOTYPE ONLY — NOT RELEASE QUALIFIED — DO NOT MERGE INTO MAIN\n\n"
        f"export const TOKENS = Object.freeze({encoded});\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    javascript = render_javascript()
    if args.check:
        current = TARGET.is_file() and TARGET.read_text(encoding="utf-8") == rendered
        current_js = JS_TARGET.is_file() and JS_TARGET.read_text(encoding="utf-8") == javascript
        return 0 if current and current_js else 1
    TARGET.write_text(rendered, encoding="utf-8", newline="\n")
    JS_TARGET.write_text(javascript, encoding="utf-8", newline="\n")
    print(TARGET)
    print(JS_TARGET)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
