#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Render the V4 comparison reports from the contract and the results.

The matrices are generated rather than written, for the same reason the
qualification reports are: a report that says a gate passed while the data says
``NOT_RUN`` is precisely the discrepancy the evidence model exists to prevent,
and the cheapest way to prevent it is to have one source.

Prose that is genuinely editorial lives in the report files' preambles here.
Every table below a preamble comes from the JSON.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import v4  # noqa: E402

ROOT = v4.ROOT
OUT = ROOT / "visual-v4"

HEADER = """<!--
SPDX-FileCopyrightText: 2026 ComradeArt
SPDX-License-Identifier: GPL-3.0-or-later
-->

<!-- GENERATED by visual-v4/tools/render_reports.py — do not edit by hand.
     Every state in this file comes from visual-v4/contract/measured-results.json.
     To change a result, measure something and record it there. -->

"""

NOTICE = """> **VISUAL OR SHELL DEVELOPMENT**
> **NOT RELEASE QUALIFIED**
> **DO NOT MERGE INTO MAIN WITHOUT AN EXPLICIT PRODUCTION INTEGRATION DECISION**
> **GNOME REMAINS THE SUPPORTED FALLBACK**

"""

# report file -> (title, group filter or None, preamble)
REPORTS = {
    "ACCESSIBILITY_COMPARISON.md": (
        "Accessibility comparison",
        {"accessibility"},
        "Accessibility carries the single largest weight in the scorecard, 18 of 100, because it "
        "is the requirement most often deferred and least often recoverable late. A label is not "
        "an accessible interface and a widget tree is not a screen-reader session: this matrix "
        "passes only when Orca, or an equivalent assistive technology, actually navigates the "
        "Bunny shell.",
    ),
    "INPUT_METHOD_COMPARISON.md": (
        "Input method comparison",
        {"input-methods"},
        "An input method passes only when real non-Latin text reaches a real application. "
        "Advertising `text-input-v3` or `input-method-v2` is not an input path; it is a promise "
        "that one could exist. Japanese, Chinese and Korean are tested separately because they "
        "fail separately, and candidate-popup positioning is tested because an IME whose "
        "candidate window lands in the wrong place is unusable even when the text arrives.",
    ),
    "SCREEN_SHARING_COMPARISON.md": (
        "Screen sharing and portal comparison",
        {"screen-sharing"},
        "Screen sharing passes only when an external client receives actual frames through "
        "PipeWire after explicit portal approval. A portal that returns a node id, a stream that "
        "negotiates and delivers nothing, and a screenshot API that writes a black PNG all fail "
        "this matrix. The approval step is part of the test, not a precondition to it.",
    ),
    "SECURITY_BOUNDARY_COMPARISON.md": (
        "Security boundary comparison",
        {"session-lock"},
        "The lock screen is the one surface where a compositor bug becomes a security failure "
        "rather than a usability one. This matrix therefore tests the boundary by breaking it: "
        "an invalid password must refuse, a crashing lock client must not expose the session, "
        "and unlock must go through PAM rather than around it.\n\n"
        "Character Mode policy applies here and is not negotiable: the guide character never "
        "appears on a password or authentication screen, and an approval pose never replaces "
        "approval controls.",
    ),
    "PERFORMANCE_COMPARISON.md": (
        "Performance comparison",
        {"rendering", "display"},
        "Every figure in the C6 performance contract is currently `UNMEASURED`.\n\n"
        "This is deliberate. The contract says not to report a frame rate from an environment "
        "that presents too few frames to support the calculation, and this environment presents "
        "none: there is no DRM device, so there is no page-flip and no vblank to pace against, "
        "and rendering falls to a software rasteriser. A frame time measured here would describe "
        "the CPU, and publishing it as a compositor figure would be the most quietly misleading "
        "number in the whole programme.",
    ),
}


def matrix(contract: dict, results: dict, groups: set[str] | None) -> list[str]:
    gates = [g for g in contract["gates"] if groups is None or g["group"] in groups]
    lines = [
        "| Gate | Mandatory | Smithay | libmutter |",
        "|---|---|---|---|",
    ]
    by_arm = {
        arm: {r["id"]: r for r in results["arms"][arm]["results"]} for arm in contract["arms"]
    }
    for gate in gates:
        mand = "**yes**" if gate["mandatory"] else "no"
        smi = by_arm["smithay"][gate["id"]]["state"]
        mut = by_arm["libmutter"][gate["id"]]["state"]
        lines.append(f"| {gate['description']} | {mand} | `{smi}` | `{mut}` |")
    lines.append("")

    reasons = sorted(
        {
            by_arm[arm][g["id"]]["reason"]
            for g in gates
            for arm in contract["arms"]
            if by_arm[arm][g["id"]]["reason"]
        }
    )
    if reasons:
        lines.append("Recorded reasons:")
        lines.append("")
        for reason in reasons:
            lines.append(f"- {reason}")
        lines.append("")
    return lines


def write(path: Path, body: str) -> None:
    path.write_text(HEADER + NOTICE + body, encoding="utf-8", newline="\n")
    print(f"wrote {path.relative_to(ROOT)}")


def main() -> int:
    contract = v4.load(v4.CONTRACT)
    results = v4.load(v4.RESULTS)
    v4.validate(contract, results)

    for filename, (title, groups, preamble) in REPORTS.items():
        body = [f"# {title}", "", preamble, ""]
        body += matrix(contract, results, groups)
        body += [
            "## Status",
            "",
            "No gate in this matrix has been measured. Nothing here supports a framework "
            "selection, and nothing here may be cited as qualification evidence.",
            "",
        ]
        write(OUT / filename, "\n".join(body))

    # The scorecard is arithmetic, so it is generated in full.
    lines = [
        "# Framework scorecard",
        "",
        "Scores are computed by `visual-v4/tools/v4.py`, counting `PASS` and nothing else. "
        "A numeric score does not override a failed or unmeasured mandatory gate, and the "
        "verdict function never consults the score until every mandatory gate is satisfied.",
        "",
        "| Category | Weight | Smithay | libmutter |",
        "|---|---|---|---|",
    ]
    weights = contract["scorecard"]
    _, smi = v4.score(contract, results, "smithay")
    _, mut = v4.score(contract, results, "libmutter")
    for category, weight in sorted(weights.items(), key=lambda kv: -kv[1]):
        lines.append(f"| {category} | {weight} | {smi[category]} | {mut[category]} |")
    total_s, _ = v4.score(contract, results, "smithay")
    total_m, _ = v4.score(contract, results, "libmutter")
    lines += [
        f"| **total** | **100** | **{total_s}** | **{total_m}** |",
        "",
        "Three categories — `security-boundary-ownership` (8), `maintenance-burden` (7) and "
        "`bunny-visual-policy-independence` (5) — carry no runtime gate in the shared contract, "
        "because they are architectural judgements rather than things a harness can execute. "
        "They score zero here rather than being redistributed across the measurable categories, "
        "so the maximum a purely measured arm can currently reach is 80. Inflating an arm to 100 "
        "by spreading unmeasurable weight over measured gates would be the same error as calling "
        "`NOT_RUN` a pass.",
        "",
        "## Status",
        "",
        f"Smithay scores {total_s}. libmutter scores {total_m}. Neither number means anything yet: "
        "both arms have every mandatory gate unsatisfied, so the scorecard is reporting the "
        "absence of measurement, not a comparison between frameworks.",
        "",
    ]
    write(OUT / "FRAMEWORK_SCORECARD.md", "\n".join(lines))

    # And the decision, which is derived, never chosen.
    decision, reasons = v4.verdict(contract, results)
    lines = [
        "# Framework decision",
        "",
        f"## Verdict: `{decision}`",
        "",
        "C9 permits exactly five verdicts: `SELECT_SMITHAY`, `SELECT_LIBMUTTER`, "
        "`CONTINUE_DUAL_TRACK`, `REOPEN_FRAMEWORK_SEARCH`, `NATIVE_SHELL_NOT_READY`.",
        "",
        "**None of them has been earned, so none is recorded.** `WITHHELD` is not a sixth "
        "verdict; it is the absence of one. C9 also says not to force a winner, and choosing "
        "between two unmeasured arms would be exactly that — a coin toss wearing a rationale.",
        "",
        "The verdict is computed by `v4.verdict`, which requires every mandatory gate of an arm "
        "to be `PASS` before that arm can be selected. It is not a field anyone edits.",
        "",
        "## Why each arm is disqualified",
        "",
    ]
    for reason in reasons:
        lines.append(f"- {reason}")
    lines += [
        "",
        "## What would change this",
        "",
        "Two of the eight mandatory gates — `gpu-rendering` and `two-output-presentation` — are "
        "`NOT_AVAILABLE` rather than `NOT_RUN`. They are not waiting on effort; they are waiting "
        "on hardware. The probe in `visual-v4/evidence/environment-probe-wsl2-fedora44.txt` "
        "records why: no `/dev/dri`, and a software rasteriser.",
        "",
        "So V4 cannot conclude on the current host at all, however much of the remaining work is "
        "done here. It needs a Linux machine with a real DRM device and two real outputs. On such "
        "a host the other six mandatory gates become ordinary engineering.",
        "",
        "Until then the operative position is unchanged and is not a verdict about the "
        "frameworks: **GNOME remains the supported architecture**, the native shell remains "
        "experimental, and no prototype may be described as release-qualified.",
        "",
    ]
    write(OUT / "FRAMEWORK_DECISION.md", "\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
