"""The stable evidence model: one record per requirement, fail-closed.

Every stable requirement carries an id, a description, an evidence *type*, a
reference to the artifact that proves it, the time it was generated, the source
commit it was generated from, a result, a reviewer, an optional expiry, a waiver
status, and a blocker status.

Four ways an evidence record can lie are checked rather than trusted:

* **Forgery.** A record naming an artifact carries that artifact's SHA-256. The
  gate recomputes it. A record claiming PASS against a file that does not exist,
  or whose bytes changed, fails.
* **Staleness.** A record past ``expiresAt`` blocks, whatever its result.
* **Wrong commit.** A record generated from a different source commit than the
  one under evaluation blocks. Evidence does not transfer between commits.
* **Unreviewed waivers.** A waiver needs a reviewer and a reference, and can
  never cover a category the release blockers list as non-waivable.

``UNKNOWN``, ``NOT_RUN`` and ``BLOCKED`` are all blocking, as is any category
with no record at all. There is no code path that treats absence as success.
"""

from __future__ import annotations

from dataclasses import dataclass
import datetime as _datetime
import hashlib
import json
from pathlib import Path
import re
from typing import Any, Iterable, Mapping

from release import PASSING_RESULTS, RESULTS, SCHEMA_VERSION

#: The twenty evidence categories the brief requires.
EVIDENCE_CATEGORIES = (
    "Build",
    "Signing",
    "Vulnerability",
    "Licence",
    "Installer",
    "Encryption",
    "Secure Boot",
    "Update",
    "Rollback",
    "Recovery",
    "Migration",
    "Multi-user",
    "Local-only",
    "Bunny-disabled",
    "Privacy",
    "Accessibility",
    "Hardware",
    "Performance",
    "Soak",
    "Support",
)

#: How a record was produced. ``third-party-report`` and ``human-approval``
#: cannot be generated by this repository and are the categories that keep a
#: self-assessment from being mistaken for an external one.
EVIDENCE_TYPES = (
    "command-output",
    "artifact-digest",
    "generated-report",
    "runtime-capture",
    "physical-hardware-report",
    "third-party-report",
    "human-approval",
)

#: Categories that ``docs/STABLE_RELEASE_BLOCKERS.md`` says no acceptance can
#: waive. Encoded so a waiver on one of them is a validation error, not a
#: judgement call.
NON_WAIVABLE_CATEGORIES = frozenset(
    {"Encryption", "Signing", "Recovery", "Privacy", "Accessibility", "Multi-user"}
)

_RFC3339 = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$")
_SHA256 = re.compile(r"^[0-9a-f]{64}$")
_COMMIT = re.compile(r"^[0-9a-f]{40}$")

_REQUIRED_FIELDS = (
    "id",
    "category",
    "description",
    "evidenceType",
    "evidenceReference",
    "generatedAt",
    "sourceCommit",
    "result",
    "reviewer",
)
_OPTIONAL_FIELDS = ("expiresAt", "contentDigest", "waiver", "notes")


class EvidenceError(ValueError):
    """Raised when an evidence record is malformed, forged, stale or overclaims."""


def _parse_time(value: str, *, field: str, record_id: str) -> _datetime.datetime:
    if not isinstance(value, str) or not _RFC3339.match(value):
        raise EvidenceError(f"{record_id}: {field} must be an RFC 3339 timestamp")
    return _datetime.datetime.fromisoformat(value.replace("Z", "+00:00"))


@dataclass(frozen=True)
class Waiver:
    reason: str
    reviewer: str
    reference: str
    approvedAt: str

    def as_dict(self) -> dict[str, Any]:
        return {
            "reason": self.reason,
            "reviewer": self.reviewer,
            "reference": self.reference,
            "approvedAt": self.approvedAt,
        }


@dataclass(frozen=True)
class EvidenceRecord:
    id: str
    category: str
    description: str
    evidenceType: str
    evidenceReference: str
    generatedAt: str
    sourceCommit: str
    result: str
    reviewer: str
    expiresAt: str | None = None
    contentDigest: str | None = None
    waiver: Waiver | None = None
    notes: str = ""

    def as_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "category": self.category,
            "description": self.description,
            "evidenceType": self.evidenceType,
            "evidenceReference": self.evidenceReference,
            "generatedAt": self.generatedAt,
            "sourceCommit": self.sourceCommit,
            "result": self.result,
            "reviewer": self.reviewer,
            "expiresAt": self.expiresAt,
            "contentDigest": self.contentDigest,
            "waiver": self.waiver.as_dict() if self.waiver else None,
            "notes": self.notes,
        }


@dataclass(frozen=True)
class RecordVerdict:
    record: EvidenceRecord
    blocking: bool
    reasons: tuple[str, ...]

    def as_dict(self) -> dict[str, Any]:
        return {**self.record.as_dict(), "blocking": self.blocking, "blockingReasons": list(self.reasons)}


def parse_record(record: Mapping[str, Any]) -> EvidenceRecord:
    """Structural validation only. Trust checks happen in :func:`verify_record`."""
    if not isinstance(record, Mapping):
        raise EvidenceError("evidence record must be an object")
    record_id = str(record.get("id", "<unnamed>"))

    unexpected = sorted(set(record) - set(_REQUIRED_FIELDS) - set(_OPTIONAL_FIELDS))
    if unexpected:
        raise EvidenceError(f"{record_id}: unknown evidence fields: {', '.join(unexpected)}")
    missing = [name for name in _REQUIRED_FIELDS if name not in record]
    if missing:
        raise EvidenceError(f"{record_id}: missing evidence fields: {', '.join(missing)}")

    if record["category"] not in EVIDENCE_CATEGORIES:
        raise EvidenceError(f"{record_id}: category must be one of {', '.join(EVIDENCE_CATEGORIES)}")
    if record["evidenceType"] not in EVIDENCE_TYPES:
        raise EvidenceError(f"{record_id}: evidenceType must be one of {', '.join(EVIDENCE_TYPES)}")
    if record["result"] not in RESULTS:
        raise EvidenceError(f"{record_id}: result must be one of {', '.join(RESULTS)}")

    for name in ("description", "evidenceReference", "reviewer"):
        if not isinstance(record[name], str) or not record[name].strip():
            raise EvidenceError(f"{record_id}: {name} must be a non-empty string")

    _parse_time(record["generatedAt"], field="generatedAt", record_id=record_id)
    if record.get("expiresAt") is not None:
        _parse_time(record["expiresAt"], field="expiresAt", record_id=record_id)

    commit = record["sourceCommit"]
    if not isinstance(commit, str) or not _COMMIT.match(commit):
        raise EvidenceError(f"{record_id}: sourceCommit must be a full 40-character commit sha")

    digest = record.get("contentDigest")
    if digest is not None and (not isinstance(digest, str) or not _SHA256.match(digest)):
        raise EvidenceError(f"{record_id}: contentDigest must be a lowercase hex SHA-256")

    waiver_value = record.get("waiver")
    waiver: Waiver | None = None
    if waiver_value is not None:
        if not isinstance(waiver_value, Mapping):
            raise EvidenceError(f"{record_id}: waiver must be an object")
        for name in ("reason", "reviewer", "reference", "approvedAt"):
            if not waiver_value.get(name):
                raise EvidenceError(f"{record_id}: waiver missing {name}")
        _parse_time(waiver_value["approvedAt"], field="waiver.approvedAt", record_id=record_id)
        if record["category"] in NON_WAIVABLE_CATEGORIES:
            raise EvidenceError(
                f"{record_id}: {record['category']} evidence cannot be waived; "
                "docs/STABLE_RELEASE_BLOCKERS.md forbids acceptance of this category"
            )
        waiver = Waiver(
            reason=str(waiver_value["reason"]),
            reviewer=str(waiver_value["reviewer"]),
            reference=str(waiver_value["reference"]),
            approvedAt=str(waiver_value["approvedAt"]),
        )

    return EvidenceRecord(
        id=record_id,
        category=record["category"],
        description=record["description"],
        evidenceType=record["evidenceType"],
        evidenceReference=record["evidenceReference"],
        generatedAt=record["generatedAt"],
        sourceCommit=commit,
        result=record["result"],
        reviewer=record["reviewer"],
        expiresAt=record.get("expiresAt"),
        contentDigest=digest,
        waiver=waiver,
        notes=str(record.get("notes", "")),
    )


def file_digest(path: Path) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def verify_record(
    record: EvidenceRecord,
    *,
    root: Path,
    sourceCommit: str,
    now: _datetime.datetime,
    externalReviewers: Iterable[str] = (),
) -> RecordVerdict:
    """Decide whether one record blocks, and say exactly why."""
    reasons: list[str] = []

    if record.result not in PASSING_RESULTS:
        reasons.append(f"result is {record.result}; only PASS is non-blocking")

    if record.sourceCommit != sourceCommit:
        reasons.append(
            f"generated from commit {record.sourceCommit[:12]} but the candidate is "
            f"{sourceCommit[:12]}; evidence does not transfer between commits"
        )

    if record.expiresAt is not None:
        expires = _parse_time(record.expiresAt, field="expiresAt", record_id=record.id)
        if expires <= now:
            reasons.append(f"expired at {record.expiresAt}")

    # Forgery check. A record that points at an artifact must point at the
    # artifact it was generated from.
    if record.evidenceType in {"command-output", "artifact-digest", "generated-report", "runtime-capture"}:
        target = (root / record.evidenceReference).resolve()
        try:
            target.relative_to(root.resolve())
        except ValueError:
            reasons.append(f"evidenceReference {record.evidenceReference} escapes the repository")
        else:
            if not target.is_file():
                reasons.append(f"evidence artifact {record.evidenceReference} does not exist")
            elif record.contentDigest is None:
                reasons.append("evidence artifact present but no contentDigest recorded; cannot detect substitution")
            else:
                actual = file_digest(target)
                if actual != record.contentDigest:
                    reasons.append(
                        f"evidence artifact digest mismatch: recorded {record.contentDigest[:12]}, "
                        f"actual {actual[:12]}"
                    )

    # An independent claim needs an independent reviewer.
    if record.evidenceType in {"third-party-report", "physical-hardware-report"}:
        external = set(externalReviewers)
        if record.reviewer not in external:
            reasons.append(
                f"evidenceType {record.evidenceType} names reviewer {record.reviewer!r}, who is not a "
                "registered independent party; a self-review is not an independent review"
            )

    # A waiver is recorded, never applied. Accepting one is a release-approver
    # decision, so the record stays blocking and the waiver is surfaced in the
    # report rather than silently clearing the result.
    if record.waiver is not None and record.result not in PASSING_RESULTS:
        reasons.append(
            f"result {record.result} carries a waiver from {record.waiver.reviewer} "
            f"({record.waiver.reference}); a waiver is recorded, not applied automatically"
        )

    return RecordVerdict(record=record, blocking=bool(reasons), reasons=tuple(reasons))


@dataclass(frozen=True)
class EvidenceReport:
    sourceCommit: str
    evaluatedAt: str
    verdicts: tuple[RecordVerdict, ...]
    missingCategories: tuple[str, ...]

    @property
    def blocked(self) -> bool:
        return bool(self.missingCategories) or any(verdict.blocking for verdict in self.verdicts)

    def as_dict(self) -> dict[str, Any]:
        blocking = [verdict for verdict in self.verdicts if verdict.blocking]
        by_category: dict[str, list[str]] = {}
        for verdict in self.verdicts:
            by_category.setdefault(verdict.record.category, []).append(verdict.record.id)
        return {
            "schemaVersion": SCHEMA_VERSION,
            "sourceCommit": self.sourceCommit,
            "evaluatedAt": self.evaluatedAt,
            "categories": {name: sorted(by_category.get(name, [])) for name in EVIDENCE_CATEGORIES},
            "missingCategories": list(self.missingCategories),
            "recordCount": len(self.verdicts),
            "blockingRecordCount": len(blocking),
            "blockingRecords": [verdict.as_dict() for verdict in blocking],
            "passingRecords": [
                verdict.record.id for verdict in self.verdicts if not verdict.blocking
            ],
            "blocked": self.blocked,
            "note": (
                "A category with no record is blocking. Unknown, expired, wrong-commit and "
                "digest-mismatched records are blocking. Waivers are recorded, never applied "
                "automatically."
            ),
        }


def evaluate_evidence(
    document: Mapping[str, Any],
    *,
    root: Path,
    sourceCommit: str,
    now: _datetime.datetime,
    externalReviewers: Iterable[str] = (),
    requiredCategories: Iterable[str] = EVIDENCE_CATEGORIES,
) -> EvidenceReport:
    """Evaluate a whole evidence document against the current commit."""
    if document.get("schemaVersion") != SCHEMA_VERSION:
        raise EvidenceError("evidence document schemaVersion is invalid")
    raw = document.get("records")
    if not isinstance(raw, list):
        raise EvidenceError("evidence document must carry a records array")

    records = [parse_record(item) for item in raw]
    identifiers = [record.id for record in records]
    duplicates = sorted({name for name in identifiers if identifiers.count(name) > 1})
    if duplicates:
        raise EvidenceError("duplicate evidence ids: " + ", ".join(duplicates))

    verdicts = tuple(
        verify_record(
            record,
            root=root,
            sourceCommit=sourceCommit,
            now=now,
            externalReviewers=externalReviewers,
        )
        for record in records
    )
    satisfied = {
        verdict.record.category for verdict in verdicts if not verdict.blocking
    }
    missing = tuple(name for name in requiredCategories if name not in satisfied)
    return EvidenceReport(
        sourceCommit=sourceCommit,
        evaluatedAt=now.isoformat().replace("+00:00", "Z"),
        verdicts=verdicts,
        missingCategories=missing,
    )


def load(path: Path) -> Any:
    return json.loads(Path(path).read_text(encoding="utf-8"))


__all__ = [
    "EVIDENCE_CATEGORIES",
    "EVIDENCE_TYPES",
    "NON_WAIVABLE_CATEGORIES",
    "EvidenceError",
    "EvidenceRecord",
    "EvidenceReport",
    "RecordVerdict",
    "Waiver",
    "evaluate_evidence",
    "file_digest",
    "parse_record",
    "verify_record",
]
