#!/usr/bin/bash
# SPDX-FileCopyrightText: 2026 ComradeArt
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Turn a resolved package lock into an immutable, signed, offline repository.
#
# This is the **materialisation** stage. Resolution decided the set once, against
# live Fedora repositories; nothing after this point resolves anything. A
# qualification build enables this repository and no other, and fails rather than
# reaching a mirror.
#
# Fedora's own signatures are preserved byte for byte. The snapshot signature is
# additional, not a replacement: re-signing the RPMs would discard the trust that
# matters most and substitute a development key for it.
#
# Usage:
#   materialise-package-snapshot.sh --snapshot-id <id> [options]
#
#   --lock PATH          resolved package lock (default: build/inputs/package-lock.json)
#   --packages DIR       where the resolved RPMs already are
#   --retention-root DIR controlled store (default: /var/lib/bunny-retention)
#   --signing-key PATH   development snapshot signing key
#                        (default: ~/.bunny-dev-keys/snapshot/dev-snapshot-signing1.pem)

set -euo pipefail

snapshot_id=""
lock="build/inputs/package-lock.json"
packages=""
retention_root="${BUNNY_RETENTION_ROOT:-/var/lib/bunny-retention}"
signing_key="${HOME}/.bunny-dev-keys/snapshot/dev-snapshot-signing1.pem"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --snapshot-id) snapshot_id="${2:?}"; shift 2 ;;
    --lock) lock="${2:?}"; shift 2 ;;
    --packages) packages="${2:?}"; shift 2 ;;
    --retention-root) retention_root="${2:?}"; shift 2 ;;
    --signing-key) signing_key="${2:?}"; shift 2 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

[[ -n "${snapshot_id}" ]] || { echo "--snapshot-id is required" >&2; exit 2; }
[[ -n "${packages}" ]] || { echo "--packages is required" >&2; exit 2; }

repository_root="$(git rev-parse --show-toplevel)"
cd "${repository_root}"

# Repository metadata must be generated by the *pinned* createrepo_c, not by
# whatever the host happens to have — different metadata can produce a different
# dependency solution, which is why createrepo_c is classified output-affecting.
# So when this runs outside the builder image and a builder lock exists, it
# re-executes itself inside the builder rather than using the host's tools or
# failing with "missing required command".
if [[ "${BUNNY_BUILDER_IMAGE:-0}" != "1" && -f build/inputs/builder-image-lock.json ]]; then
  builder_layout="$(python3 -c '
import json
lock = json.load(open("build/inputs/builder-image-lock.json"))
print(lock["builderReference"].split("@", 1)[0])
')"
  echo "==> re-executing inside the pinned builder image"
  echo "    ${builder_layout}"
  exec podman run --rm \
    --volume "${repository_root}:/workspace:z" \
    --volume "${retention_root}:${retention_root}:z" \
    --volume "${packages}:${packages}:ro,z" \
    --volume "${HOME}/.bunny-dev-keys:/root/.bunny-dev-keys:z" \
    --env BUNNY_BUILDER_IMAGE=1 \
    --env "BUNNY_RETENTION_ROOT=${retention_root}" \
    --workdir /workspace \
    --entrypoint /usr/bin/bash \
    "oci:${builder_layout}:builder" \
    scripts/supply-chain/materialise-package-snapshot.sh \
      --snapshot-id "${snapshot_id}" \
      --lock "${lock}" \
      --packages "${packages}" \
      --retention-root "${retention_root}" \
      --signing-key "/root/.bunny-dev-keys/snapshot/$(basename "${signing_key}")"
fi

for command in createrepo_c rpmkeys openssl python3 git; do
  command -v "${command}" >/dev/null 2>&1 || { echo "missing required command: ${command}" >&2; exit 3; }
done
[[ -f "${lock}" ]] || { echo "no package lock at ${lock}" >&2; exit 2; }

snapshot="${retention_root}/package-snapshots/${snapshot_id}"
echo "==> materialising snapshot ${snapshot_id} at ${snapshot}"
rm -rf "${snapshot}"
mkdir -p "${snapshot}/packages" "${snapshot}/repodata"

echo "==> copying and verifying every locked package"
python3 scripts/supply-chain/collect-snapshot-packages.py \
  --lock "${lock}" \
  --source "${packages}" \
  --destination "${snapshot}/packages"

echo "==> re-verifying every signature in the materialised snapshot"
# Verified again here rather than trusted from resolution. Copying is where a
# file can change, and a snapshot that verified its inputs but not its contents
# would be checking the wrong thing.
failed=0
while IFS= read -r rpm; do
  if ! rpmkeys --checksig "${rpm}" | grep -q 'signatures OK'; then
    echo "  FAIL $(basename "${rpm}")" >&2
    failed=1
  fi
done < <(find "${snapshot}/packages" -name '*.rpm')
if [[ "${failed}" != "0" ]]; then
  echo "BLOCKED: at least one package in the snapshot does not verify." >&2
  exit 2
fi
echo "    all signatures verified"

echo "==> copying the Fedora signing keys into the snapshot"
# The keys travel with the packages they verify.
#
# The build itself reads them from the base image's filesystem, which works
# because the base image is where the build runs. It leaves the *published*
# snapshot unverifiable on its own: a consumer who pulled it would have to fetch
# Fedora's keys from the network to check a single signature, reintroducing at
# verification time the exact dependency the snapshot exists to remove.
#
# Found by running verify-published-inputs.py against the published artifact,
# which refuses a snapshot shipping no key rather than falling back to a key
# from somewhere else.
#
# They come out of the retained base by digest, so their provenance is the same
# pinned image the packages were resolved against — not a download, and not
# whatever the build host happens to trust.
mkdir -p "${snapshot}/keys"
base_layout="$(python3 -c '
import json
print(json.load(open("build/inputs/base-image-lock.json"))["retainedLocation"])
')"
# Only this release's keys, and only the architectures this snapshot is for. A
# glob of every Fedora key ever published matched 300 of them once, which is the
# opposite of pinning.
#
# The release and architecture are derived rather than assumed: a snapshot id of
# `fedora-44-beta-20260730` names the release, and the package lock names the
# architecture it was resolved for. Guessing either would ship a key that
# verifies nothing.
release="$(printf '%s' "${snapshot_id}" | sed -n 's/^fedora-\([0-9][0-9]*\)-.*/\1/p')"
if [[ -z "${release}" ]]; then
  echo "BLOCKED: cannot read a Fedora release from the snapshot id ${snapshot_id}." >&2
  echo "The signing keys are per release; shipping the wrong one verifies nothing." >&2
  exit 2
fi
architecture="$(python3 -c '
import json, sys
print(json.load(open(sys.argv[1])).get("architecture", "x86_64"))
' "${lock}")"

# Read out of the layout directly rather than through a container runtime. This
# step runs *inside* the pinned builder, where the host's
# `localhost/bunny-os-retained-base:…` tag is not an image but a hostname —
# podman resolves it as a registry and fails with a connection refused, which is
# a confusing way to say the tag belongs to another machine's store.
python3 scripts/supply-chain/extract-oci-layout-paths.py \
  --layout "${base_layout}" \
  --reference retained \
  --pattern "etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-${release}-primary" \
  --pattern "etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-${release}-${architecture}" \
  --destination "${snapshot}/keys" \
  --flatten \
  --require 2

echo "==> generating repository metadata"
# --excludes keys: the keys are shipped beside the repository, not as part of it.
# createrepo_c would otherwise be describing files that are not packages.
createrepo_c --quiet --general-compress-type=gz --excludes 'keys/*' "${snapshot}"

# The metadata digest is over repomd.xml, which is itself a manifest of every
# other metadata file with their checksums. Signing repomd.xml therefore covers
# the whole of repodata, which is why `repo_gpgcheck=1` is meaningful.
metadata_digest="$(sha256sum "${snapshot}/repodata/repomd.xml" | awk '{print $1}')"
echo "    repomd.xml ${metadata_digest}"

echo "==> writing the snapshot manifest"
python3 scripts/supply-chain/write-snapshot-lock.py \
  --lock "${lock}" \
  --snapshot-id "${snapshot_id}" \
  --snapshot-root "${snapshot}" \
  --metadata-digest "${metadata_digest}" \
  --signing-key "${signing_key}"

echo
echo "snapshot ${snapshot_id} materialised"
echo "  packages  $(find "${snapshot}/packages" -name '*.rpm' | wc -l)"
echo "  location  ${snapshot}"
echo
echo "The development snapshot-signing key is not production trust. It proves the"
echo "signing path works and nothing about release authorisation; see"
echo "docs/PACKAGE_SNAPSHOTS.md for the production signing role, which does not exist."
