[Anaconda]
profile_id = bunny-os

[Installation System]
can_detect_unsupported_hardware = true

[Payload]
enable_closest_mirror = false

[Security]
selinux = 1

[User Interface]
webui = true
hidden_webui_pages = anaconda-screen-software-selection

[Storage]
default_scheme = LVM
file_system_type = ext4
allow_imperfect_devices = false

[Bootloader]
efi_dir = fedora
